/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailDeliveryInfo
 */
export interface EmailDeliveryInfo {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof EmailDeliveryInfo
     */
    readonly $schema?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EmailDeliveryInfo
     */
    enabled: boolean;
    /**
     * 
     * @type {string}
     * @memberof EmailDeliveryInfo
     */
    from: string;
    /**
     * 
     * @type {string}
     * @memberof EmailDeliveryInfo
     */
    host: string;
}

/**
 * Check if a given object implements the EmailDeliveryInfo interface.
 */
export function instanceOfEmailDeliveryInfo(value: object): value is EmailDeliveryInfo {
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('host' in value) || value['host'] === undefined) return false;
    return true;
}

export function EmailDeliveryInfoFromJSON(json: any): EmailDeliveryInfo {
    return EmailDeliveryInfoFromJSONTyped(json, false);
}

export function EmailDeliveryInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailDeliveryInfo {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'enabled': json['enabled'],
        'from': json['from'],
        'host': json['host'],
    };
}

export function EmailDeliveryInfoToJSON(json: any): EmailDeliveryInfo {
    return EmailDeliveryInfoToJSONTyped(json, false);
}

export function EmailDeliveryInfoToJSONTyped(value?: Omit<EmailDeliveryInfo, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
        'from': value['from'],
        'host': value['host'],
    };
}

