/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ForgotPasswordRequest
 */
export interface ForgotPasswordRequest {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof ForgotPasswordRequest
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof ForgotPasswordRequest
     */
    email: string;
}

/**
 * Check if a given object implements the ForgotPasswordRequest interface.
 */
export function instanceOfForgotPasswordRequest(value: object): value is ForgotPasswordRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function ForgotPasswordRequestFromJSON(json: any): ForgotPasswordRequest {
    return ForgotPasswordRequestFromJSONTyped(json, false);
}

export function ForgotPasswordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForgotPasswordRequest {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'email': json['email'],
    };
}

export function ForgotPasswordRequestToJSON(json: any): ForgotPasswordRequest {
    return ForgotPasswordRequestToJSONTyped(json, false);
}

export function ForgotPasswordRequestToJSONTyped(value?: Omit<ForgotPasswordRequest, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

