/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Link
 */
export interface Link {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof Link
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof Link
     */
    color: string;
    /**
     * 
     * @type {string}
     * @memberof Link
     */
    icon: string;
    /**
     * 
     * @type {string}
     * @memberof Link
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Link
     */
    link: string;
    /**
     * 
     * @type {string}
     * @memberof Link
     */
    sectionId: string;
    /**
     * 
     * @type {string}
     * @memberof Link
     */
    title: string;
}

/**
 * Check if a given object implements the Link interface.
 */
export function instanceOfLink(value: object): value is Link {
    if (!('color' in value) || value['color'] === undefined) return false;
    if (!('icon' in value) || value['icon'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('link' in value) || value['link'] === undefined) return false;
    if (!('sectionId' in value) || value['sectionId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function LinkFromJSON(json: any): Link {
    return LinkFromJSONTyped(json, false);
}

export function LinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): Link {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'color': json['color'],
        'icon': json['icon'],
        'id': json['id'],
        'link': json['link'],
        'sectionId': json['sectionId'],
        'title': json['title'],
    };
}

export function LinkToJSON(json: any): Link {
    return LinkToJSONTyped(json, false);
}

export function LinkToJSONTyped(value?: Omit<Link, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'color': value['color'],
        'icon': value['icon'],
        'id': value['id'],
        'link': value['link'],
        'sectionId': value['sectionId'],
        'title': value['title'],
    };
}

