/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document:
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LinkOrderItem } from './LinkOrderItem';
import {
    LinkOrderItemFromJSON,
    LinkOrderItemFromJSONTyped,
    LinkOrderItemToJSON,
    LinkOrderItemToJSONTyped,
} from './LinkOrderItem';

/**
 *
 * @export
 * @interface LinkOrderRequestBody
 */
export interface LinkOrderRequestBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof LinkOrderRequestBody
     */
    readonly $schema?: string;
    /**
     *
     * @type {Array<LinkOrderItem>}
     * @memberof LinkOrderRequestBody
     */
    links: Array<LinkOrderItem> | null;
}

/**
 * Check if a given object implements the LinkOrderRequestBody interface.
 */
export function instanceOfLinkOrderRequestBody(value: object): value is LinkOrderRequestBody {
    if (!('links' in value) || value['links'] === undefined) return false;
    return true;
}

export function LinkOrderRequestBodyFromJSON(json: any): LinkOrderRequestBody {
    return LinkOrderRequestBodyFromJSONTyped(json, false);
}

export function LinkOrderRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkOrderRequestBody {
    if (json == null) {
        return json;
    }
    return {

        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'links': (json['links'] == null ? null : (json['links'] as Array<any>).map(LinkOrderItemFromJSON)),
    };
}

export function LinkOrderRequestBodyToJSON(json: any): LinkOrderRequestBody {
    return LinkOrderRequestBodyToJSONTyped(json, false);
}

export function LinkOrderRequestBodyToJSONTyped(value?: Omit<LinkOrderRequestBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'links': (value['links'] == null ? null : (value['links'] as Array<any>).map(LinkOrderItemToJSON)),
    };
}

