/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document:
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface LinkOrderFailure
 */
export interface LinkOrderFailure {
    /**
     *
     * @type {string}
     * @memberof LinkOrderFailure
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof LinkOrderFailure
     */
    reason: string;
}

/**
 * Check if a given object implements the LinkOrderFailure interface.
 */
export function instanceOfLinkOrderFailure(value: object): value is LinkOrderFailure {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function LinkOrderFailureFromJSON(json: any): LinkOrderFailure {
    return LinkOrderFailureFromJSONTyped(json, false);
}

export function LinkOrderFailureFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkOrderFailure {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'reason': json['reason'],
    };
}

export function LinkOrderFailureToJSON(json: any): LinkOrderFailure {
    return LinkOrderFailureToJSONTyped(json, false);
}

export function LinkOrderFailureToJSONTyped(value?: LinkOrderFailure | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'reason': value['reason'],
    };
}

