/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LinkOrderItem
 */
export interface LinkOrderItem {
    /**
     * 
     * @type {string}
     * @memberof LinkOrderItem
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof LinkOrderItem
     */
    order: number;
}

/**
 * Check if a given object implements the LinkOrderItem interface.
 */
export function instanceOfLinkOrderItem(value: object): value is LinkOrderItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('order' in value) || value['order'] === undefined) return false;
    return true;
}

export function LinkOrderItemFromJSON(json: any): LinkOrderItem {
    return LinkOrderItemFromJSONTyped(json, false);
}

export function LinkOrderItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkOrderItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'order': json['order'],
    };
}

export function LinkOrderItemToJSON(json: any): LinkOrderItem {
    return LinkOrderItemToJSONTyped(json, false);
}

export function LinkOrderItemToJSONTyped(value?: LinkOrderItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'order': value['order'],
    };
}

