/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LinkOrderFailure } from './LinkOrderFailure';
import {
    LinkOrderFailureFromJSON,
    LinkOrderFailureFromJSONTyped,
    LinkOrderFailureToJSON,
    LinkOrderFailureToJSONTyped,
} from './LinkOrderFailure';

/**
 * 
 * @export
 * @interface LinkOrderResponseBody
 */
export interface LinkOrderResponseBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof LinkOrderResponseBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {Array<LinkOrderFailure>}
     * @memberof LinkOrderResponseBody
     */
    failures: Array<LinkOrderFailure> | null;
}

/**
 * Check if a given object implements the LinkOrderResponseBody interface.
 */
export function instanceOfLinkOrderResponseBody(value: object): value is LinkOrderResponseBody {
    if (!('failures' in value) || value['failures'] === undefined) return false;
    return true;
}

export function LinkOrderResponseBodyFromJSON(json: any): LinkOrderResponseBody {
    return LinkOrderResponseBodyFromJSONTyped(json, false);
}

export function LinkOrderResponseBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkOrderResponseBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'failures': (json['failures'] == null ? null : (json['failures'] as Array<any>).map(LinkOrderFailureFromJSON)),
    };
}

export function LinkOrderResponseBodyToJSON(json: any): LinkOrderResponseBody {
    return LinkOrderResponseBodyToJSONTyped(json, false);
}

export function LinkOrderResponseBodyToJSONTyped(value?: Omit<LinkOrderResponseBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'failures': (value['failures'] == null ? null : (value['failures'] as Array<any>).map(LinkOrderFailureToJSON)),
    };
}

