/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LinkBase
 */
export interface LinkBase {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof LinkBase
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof LinkBase
     */
    color: string;
    /**
     * 
     * @type {string}
     * @memberof LinkBase
     */
    icon: string;
    /**
     * 
     * @type {string}
     * @memberof LinkBase
     */
    link: string;
    /**
     * 
     * @type {string}
     * @memberof LinkBase
     */
    sectionId: string;
    /**
     * 
     * @type {string}
     * @memberof LinkBase
     */
    title: string;
}

/**
 * Check if a given object implements the LinkBase interface.
 */
export function instanceOfLinkBase(value: object): value is LinkBase {
    if (!('color' in value) || value['color'] === undefined) return false;
    if (!('icon' in value) || value['icon'] === undefined) return false;
    if (!('link' in value) || value['link'] === undefined) return false;
    if (!('sectionId' in value) || value['sectionId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function LinkBaseFromJSON(json: any): LinkBase {
    return LinkBaseFromJSONTyped(json, false);
}

export function LinkBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkBase {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'color': json['color'],
        'icon': json['icon'],
        'link': json['link'],
        'sectionId': json['sectionId'],
        'title': json['title'],
    };
}

export function LinkBaseToJSON(json: any): LinkBase {
    return LinkBaseToJSONTyped(json, false);
}

export function LinkBaseToJSONTyped(value?: Omit<LinkBase, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'color': value['color'],
        'icon': value['icon'],
        'link': value['link'],
        'sectionId': value['sectionId'],
        'title': value['title'],
    };
}

