/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OidcLoginResponseBody
 */
export interface OidcLoginResponseBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof OidcLoginResponseBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof OidcLoginResponseBody
     */
    authorizationUrl: string;
    /**
     * 
     * @type {string}
     * @memberof OidcLoginResponseBody
     */
    state: string;
}

/**
 * Check if a given object implements the OidcLoginResponseBody interface.
 */
export function instanceOfOidcLoginResponseBody(value: object): value is OidcLoginResponseBody {
    if (!('authorizationUrl' in value) || value['authorizationUrl'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    return true;
}

export function OidcLoginResponseBodyFromJSON(json: any): OidcLoginResponseBody {
    return OidcLoginResponseBodyFromJSONTyped(json, false);
}

export function OidcLoginResponseBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): OidcLoginResponseBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'authorizationUrl': json['authorization_url'],
        'state': json['state'],
    };
}

export function OidcLoginResponseBodyToJSON(json: any): OidcLoginResponseBody {
    return OidcLoginResponseBodyToJSONTyped(json, false);
}

export function OidcLoginResponseBodyToJSONTyped(value?: Omit<OidcLoginResponseBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'authorization_url': value['authorizationUrl'],
        'state': value['state'],
    };
}

