/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OidcCallbackRequest
 */
export interface OidcCallbackRequest {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof OidcCallbackRequest
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof OidcCallbackRequest
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof OidcCallbackRequest
     */
    state: string;
}

/**
 * Check if a given object implements the OidcCallbackRequest interface.
 */
export function instanceOfOidcCallbackRequest(value: object): value is OidcCallbackRequest {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    return true;
}

export function OidcCallbackRequestFromJSON(json: any): OidcCallbackRequest {
    return OidcCallbackRequestFromJSONTyped(json, false);
}

export function OidcCallbackRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OidcCallbackRequest {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'code': json['code'],
        'state': json['state'],
    };
}

export function OidcCallbackRequestToJSON(json: any): OidcCallbackRequest {
    return OidcCallbackRequestToJSONTyped(json, false);
}

export function OidcCallbackRequestToJSONTyped(value?: Omit<OidcCallbackRequest, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'state': value['state'],
    };
}

