/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicShelf
 */
export interface PublicShelf {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof PublicShelf
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicShelf
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof PublicShelf
     */
    footerCustomText: string;
    /**
     * 
     * @type {boolean}
     * @memberof PublicShelf
     */
    footerEnabled: boolean;
    /**
     * 
     * @type {string}
     * @memberof PublicShelf
     */
    icon: string;
    /**
     * 
     * @type {string}
     * @memberof PublicShelf
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof PublicShelf
     */
    noIndex: boolean;
    /**
     * 
     * @type {string}
     * @memberof PublicShelf
     */
    path: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof PublicShelf
     */
    theme: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof PublicShelf
     */
    title: string;
}

/**
 * Check if a given object implements the PublicShelf interface.
 */
export function instanceOfPublicShelf(value: object): value is PublicShelf {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('footerCustomText' in value) || value['footerCustomText'] === undefined) return false;
    if (!('footerEnabled' in value) || value['footerEnabled'] === undefined) return false;
    if (!('icon' in value) || value['icon'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('noIndex' in value) || value['noIndex'] === undefined) return false;
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('theme' in value) || value['theme'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function PublicShelfFromJSON(json: any): PublicShelf {
    return PublicShelfFromJSONTyped(json, false);
}

export function PublicShelfFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicShelf {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'description': json['description'],
        'footerCustomText': json['footerCustomText'],
        'footerEnabled': json['footerEnabled'],
        'icon': json['icon'],
        'id': json['id'],
        'noIndex': json['noIndex'],
        'path': json['path'],
        'theme': json['theme'],
        'title': json['title'],
    };
}

export function PublicShelfToJSON(json: any): PublicShelf {
    return PublicShelfToJSONTyped(json, false);
}

export function PublicShelfToJSONTyped(value?: Omit<PublicShelf, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'footerCustomText': value['footerCustomText'],
        'footerEnabled': value['footerEnabled'],
        'icon': value['icon'],
        'id': value['id'],
        'noIndex': value['noIndex'],
        'path': value['path'],
        'theme': value['theme'],
        'title': value['title'],
    };
}

