/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResendVerificationRequest
 */
export interface ResendVerificationRequest {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof ResendVerificationRequest
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof ResendVerificationRequest
     */
    email: string;
}

/**
 * Check if a given object implements the ResendVerificationRequest interface.
 */
export function instanceOfResendVerificationRequest(value: object): value is ResendVerificationRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function ResendVerificationRequestFromJSON(json: any): ResendVerificationRequest {
    return ResendVerificationRequestFromJSONTyped(json, false);
}

export function ResendVerificationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResendVerificationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'email': json['email'],
    };
}

export function ResendVerificationRequestToJSON(json: any): ResendVerificationRequest {
    return ResendVerificationRequestToJSONTyped(json, false);
}

export function ResendVerificationRequestToJSONTyped(value?: Omit<ResendVerificationRequest, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

