/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document:
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SectionOrderFailure
 */
export interface SectionOrderFailure {
    /**
     *
     * @type {string}
     * @memberof SectionOrderFailure
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof SectionOrderFailure
     */
    reason: string;
}

/**
 * Check if a given object implements the SectionOrderFailure interface.
 */
export function instanceOfSectionOrderFailure(value: object): value is SectionOrderFailure {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function SectionOrderFailureFromJSON(json: any): SectionOrderFailure {
    return SectionOrderFailureFromJSONTyped(json, false);
}

export function SectionOrderFailureFromJSONTyped(json: any, ignoreDiscriminator: boolean): SectionOrderFailure {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'reason': json['reason'],
    };
}

export function SectionOrderFailureToJSON(json: any): SectionOrderFailure {
    return SectionOrderFailureToJSONTyped(json, false);
}

export function SectionOrderFailureToJSONTyped(value?: SectionOrderFailure | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'reason': value['reason'],
    };
}

