/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SectionOrderItem
 */
export interface SectionOrderItem {
    /**
     * 
     * @type {string}
     * @memberof SectionOrderItem
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof SectionOrderItem
     */
    order: number;
}

/**
 * Check if a given object implements the SectionOrderItem interface.
 */
export function instanceOfSectionOrderItem(value: object): value is SectionOrderItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('order' in value) || value['order'] === undefined) return false;
    return true;
}

export function SectionOrderItemFromJSON(json: any): SectionOrderItem {
    return SectionOrderItemFromJSONTyped(json, false);
}

export function SectionOrderItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): SectionOrderItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'order': json['order'],
    };
}

export function SectionOrderItemToJSON(json: any): SectionOrderItem {
    return SectionOrderItemToJSONTyped(json, false);
}

export function SectionOrderItemToJSONTyped(value?: SectionOrderItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'order': value['order'],
    };
}

