/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Section
 */
export interface Section {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof Section
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof Section
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Section
     */
    shelfId: string;
    /**
     * 
     * @type {string}
     * @memberof Section
     */
    title: string;
}

/**
 * Check if a given object implements the Section interface.
 */
export function instanceOfSection(value: object): value is Section {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('shelfId' in value) || value['shelfId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function SectionFromJSON(json: any): Section {
    return SectionFromJSONTyped(json, false);
}

export function SectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Section {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'id': json['id'],
        'shelfId': json['shelfId'],
        'title': json['title'],
    };
}

export function SectionToJSON(json: any): Section {
    return SectionToJSONTyped(json, false);
}

export function SectionToJSONTyped(value?: Omit<Section, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'shelfId': value['shelfId'],
        'title': value['title'],
    };
}

