/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document:
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SectionOrderItem } from './SectionOrderItem';
import {
    SectionOrderItemFromJSON,
    SectionOrderItemFromJSONTyped,
    SectionOrderItemToJSON,
    SectionOrderItemToJSONTyped,
} from './SectionOrderItem';

/**
 *
 * @export
 * @interface SectionOrderRequestBody
 */
export interface SectionOrderRequestBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof SectionOrderRequestBody
     */
    readonly $schema?: string;
    /**
     *
     * @type {Array<SectionOrderItem>}
     * @memberof SectionOrderRequestBody
     */
    sections: Array<SectionOrderItem> | null;
}

/**
 * Check if a given object implements the SectionOrderRequestBody interface.
 */
export function instanceOfSectionOrderRequestBody(value: object): value is SectionOrderRequestBody {
    if (!('sections' in value) || value['sections'] === undefined) return false;
    return true;
}

export function SectionOrderRequestBodyFromJSON(json: any): SectionOrderRequestBody {
    return SectionOrderRequestBodyFromJSONTyped(json, false);
}

export function SectionOrderRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SectionOrderRequestBody {
    if (json == null) {
        return json;
    }
    return {

        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'sections': (json['sections'] == null ? null : (json['sections'] as Array<any>).map(SectionOrderItemFromJSON)),
    };
}

export function SectionOrderRequestBodyToJSON(json: any): SectionOrderRequestBody {
    return SectionOrderRequestBodyToJSONTyped(json, false);
}

export function SectionOrderRequestBodyToJSONTyped(value?: Omit<SectionOrderRequestBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'sections': (value['sections'] == null ? null : (value['sections'] as Array<any>).map(SectionOrderItemToJSON)),
    };
}

