/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SectionBase
 */
export interface SectionBase {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof SectionBase
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof SectionBase
     */
    shelfId: string;
    /**
     * 
     * @type {string}
     * @memberof SectionBase
     */
    title: string;
}

/**
 * Check if a given object implements the SectionBase interface.
 */
export function instanceOfSectionBase(value: object): value is SectionBase {
    if (!('shelfId' in value) || value['shelfId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function SectionBaseFromJSON(json: any): SectionBase {
    return SectionBaseFromJSONTyped(json, false);
}

export function SectionBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SectionBase {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'shelfId': json['shelfId'],
        'title': json['title'],
    };
}

export function SectionBaseToJSON(json: any): SectionBase {
    return SectionBaseToJSONTyped(json, false);
}

export function SectionBaseToJSONTyped(value?: Omit<SectionBase, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'shelfId': value['shelfId'],
        'title': value['title'],
    };
}

