/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SectionOrderFailure } from './SectionOrderFailure';
import {
    SectionOrderFailureFromJSON,
    SectionOrderFailureFromJSONTyped,
    SectionOrderFailureToJSON,
    SectionOrderFailureToJSONTyped,
} from './SectionOrderFailure';

/**
 * 
 * @export
 * @interface SectionOrderResponseBody
 */
export interface SectionOrderResponseBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof SectionOrderResponseBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {Array<SectionOrderFailure>}
     * @memberof SectionOrderResponseBody
     */
    failures: Array<SectionOrderFailure> | null;
}

/**
 * Check if a given object implements the SectionOrderResponseBody interface.
 */
export function instanceOfSectionOrderResponseBody(value: object): value is SectionOrderResponseBody {
    if (!('failures' in value) || value['failures'] === undefined) return false;
    return true;
}

export function SectionOrderResponseBodyFromJSON(json: any): SectionOrderResponseBody {
    return SectionOrderResponseBodyFromJSONTyped(json, false);
}

export function SectionOrderResponseBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SectionOrderResponseBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'failures': (json['failures'] == null ? null : (json['failures'] as Array<any>).map(SectionOrderFailureFromJSON)),
    };
}

export function SectionOrderResponseBodyToJSON(json: any): SectionOrderResponseBody {
    return SectionOrderResponseBodyToJSONTyped(json, false);
}

export function SectionOrderResponseBodyToJSONTyped(value?: Omit<SectionOrderResponseBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'failures': (value['failures'] == null ? null : (value['failures'] as Array<any>).map(SectionOrderFailureToJSON)),
    };
}

