/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetPasswordRequest
 */
export interface SetPasswordRequest {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof SetPasswordRequest
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof SetPasswordRequest
     */
    newPassword: string;
    /**
     * 
     * @type {string}
     * @memberof SetPasswordRequest
     */
    token: string;
}

/**
 * Check if a given object implements the SetPasswordRequest interface.
 */
export function instanceOfSetPasswordRequest(value: object): value is SetPasswordRequest {
    if (!('newPassword' in value) || value['newPassword'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function SetPasswordRequestFromJSON(json: any): SetPasswordRequest {
    return SetPasswordRequestFromJSONTyped(json, false);
}

export function SetPasswordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetPasswordRequest {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'newPassword': json['new_password'],
        'token': json['token'],
    };
}

export function SetPasswordRequestToJSON(json: any): SetPasswordRequest {
    return SetPasswordRequestToJSONTyped(json, false);
}

export function SetPasswordRequestToJSONTyped(value?: Omit<SetPasswordRequest, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'new_password': value['newPassword'],
        'token': value['token'],
    };
}

