/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Setting
 */
export interface Setting {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof Setting
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof Setting
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof Setting
     */
    languageCode: string;
    /**
     * 
     * @type {string}
     * @memberof Setting
     */
    value: string;
}

/**
 * Check if a given object implements the Setting interface.
 */
export function instanceOfSetting(value: object): value is Setting {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('languageCode' in value) || value['languageCode'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function SettingFromJSON(json: any): Setting {
    return SettingFromJSONTyped(json, false);
}

export function SettingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Setting {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'key': json['key'],
        'languageCode': json['language_code'],
        'value': json['value'],
    };
}

export function SettingToJSON(json: any): Setting {
    return SettingToJSONTyped(json, false);
}

export function SettingToJSONTyped(value?: Omit<Setting, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'language_code': value['languageCode'],
        'value': value['value'],
    };
}

