/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Setting } from './Setting';
import {
    SettingFromJSON,
    SettingFromJSONTyped,
    SettingToJSON,
    SettingToJSONTyped,
} from './Setting';

/**
 * 
 * @export
 * @interface SettingBatchRequestBody
 */
export interface SettingBatchRequestBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof SettingBatchRequestBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {Array<Setting>}
     * @memberof SettingBatchRequestBody
     */
    settings: Array<Setting> | null;
}

/**
 * Check if a given object implements the SettingBatchRequestBody interface.
 */
export function instanceOfSettingBatchRequestBody(value: object): value is SettingBatchRequestBody {
    if (!('settings' in value) || value['settings'] === undefined) return false;
    return true;
}

export function SettingBatchRequestBodyFromJSON(json: any): SettingBatchRequestBody {
    return SettingBatchRequestBodyFromJSONTyped(json, false);
}

export function SettingBatchRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SettingBatchRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'settings': (json['settings'] == null ? null : (json['settings'] as Array<any>).map(SettingFromJSON)),
    };
}

export function SettingBatchRequestBodyToJSON(json: any): SettingBatchRequestBody {
    return SettingBatchRequestBodyToJSONTyped(json, false);
}

export function SettingBatchRequestBodyToJSONTyped(value?: Omit<SettingBatchRequestBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'settings': (value['settings'] == null ? null : (value['settings'] as Array<any>).map(SettingToJSON)),
    };
}

