/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SettingPageBody } from './SettingPageBody';
import {
    SettingPageBodyFromJSON,
    SettingPageBodyFromJSONTyped,
    SettingPageBodyToJSON,
    SettingPageBodyToJSONTyped,
} from './SettingPageBody';
import type { SettingUpdateFailure } from './SettingUpdateFailure';
import {
    SettingUpdateFailureFromJSON,
    SettingUpdateFailureFromJSONTyped,
    SettingUpdateFailureToJSON,
    SettingUpdateFailureToJSONTyped,
} from './SettingUpdateFailure';

/**
 * 
 * @export
 * @interface SettingBatchResponseBody
 */
export interface SettingBatchResponseBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof SettingBatchResponseBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {Array<SettingUpdateFailure>}
     * @memberof SettingBatchResponseBody
     */
    failures: Array<SettingUpdateFailure> | null;
    /**
     * 
     * @type {SettingPageBody}
     * @memberof SettingBatchResponseBody
     */
    settings: SettingPageBody;
}

/**
 * Check if a given object implements the SettingBatchResponseBody interface.
 */
export function instanceOfSettingBatchResponseBody(value: object): value is SettingBatchResponseBody {
    if (!('failures' in value) || value['failures'] === undefined) return false;
    if (!('settings' in value) || value['settings'] === undefined) return false;
    return true;
}

export function SettingBatchResponseBodyFromJSON(json: any): SettingBatchResponseBody {
    return SettingBatchResponseBodyFromJSONTyped(json, false);
}

export function SettingBatchResponseBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SettingBatchResponseBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'failures': (json['failures'] == null ? null : (json['failures'] as Array<any>).map(SettingUpdateFailureFromJSON)),
        'settings': SettingPageBodyFromJSON(json['settings']),
    };
}

export function SettingBatchResponseBodyToJSON(json: any): SettingBatchResponseBody {
    return SettingBatchResponseBodyToJSONTyped(json, false);
}

export function SettingBatchResponseBodyToJSONTyped(value?: Omit<SettingBatchResponseBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'failures': (value['failures'] == null ? null : (value['failures'] as Array<any>).map(SettingUpdateFailureToJSON)),
        'settings': SettingPageBodyToJSON(value['settings']),
    };
}

