/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SettingUpdateFailure
 */
export interface SettingUpdateFailure {
    /**
     * 
     * @type {string}
     * @memberof SettingUpdateFailure
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof SettingUpdateFailure
     */
    languageCode: string;
    /**
     * 
     * @type {string}
     * @memberof SettingUpdateFailure
     */
    reason: string;
}

/**
 * Check if a given object implements the SettingUpdateFailure interface.
 */
export function instanceOfSettingUpdateFailure(value: object): value is SettingUpdateFailure {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('languageCode' in value) || value['languageCode'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function SettingUpdateFailureFromJSON(json: any): SettingUpdateFailure {
    return SettingUpdateFailureFromJSONTyped(json, false);
}

export function SettingUpdateFailureFromJSONTyped(json: any, ignoreDiscriminator: boolean): SettingUpdateFailure {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'languageCode': json['language_code'],
        'reason': json['reason'],
    };
}

export function SettingUpdateFailureToJSON(json: any): SettingUpdateFailure {
    return SettingUpdateFailureToJSONTyped(json, false);
}

export function SettingUpdateFailureToJSONTyped(value?: SettingUpdateFailure | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'language_code': value['languageCode'],
        'reason': value['reason'],
    };
}

