/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SettingPageBody
 */
export interface SettingPageBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof SettingPageBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof SettingPageBody
     */
    about: string;
    /**
     * 
     * @type {boolean}
     * @memberof SettingPageBody
     */
    aboutShow: boolean;
    /**
     * 
     * @type {string}
     * @memberof SettingPageBody
     */
    contact: string;
    /**
     * 
     * @type {boolean}
     * @memberof SettingPageBody
     */
    contactShow: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SettingPageBody
     */
    emailVerificationEnabled: boolean;
    /**
     * 
     * @type {string}
     * @memberof SettingPageBody
     */
    imprint: string;
    /**
     * 
     * @type {boolean}
     * @memberof SettingPageBody
     */
    imprintShow: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SettingPageBody
     */
    oidcEnabled: boolean;
    /**
     * 
     * @type {string}
     * @memberof SettingPageBody
     */
    privacyPolicy: string;
    /**
     * 
     * @type {boolean}
     * @memberof SettingPageBody
     */
    privacyPolicyShow: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SettingPageBody
     */
    redirectToDashboard: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SettingPageBody
     */
    registrationEnabled: boolean;
    /**
     * 
     * @type {string}
     * @memberof SettingPageBody
     */
    termsOfUse: string;
    /**
     * 
     * @type {boolean}
     * @memberof SettingPageBody
     */
    termsOfUseShow: boolean;
}

/**
 * Check if a given object implements the SettingPageBody interface.
 */
export function instanceOfSettingPageBody(value: object): value is SettingPageBody {
    if (!('about' in value) || value['about'] === undefined) return false;
    if (!('aboutShow' in value) || value['aboutShow'] === undefined) return false;
    if (!('contact' in value) || value['contact'] === undefined) return false;
    if (!('contactShow' in value) || value['contactShow'] === undefined) return false;
    if (!('emailVerificationEnabled' in value) || value['emailVerificationEnabled'] === undefined) return false;
    if (!('imprint' in value) || value['imprint'] === undefined) return false;
    if (!('imprintShow' in value) || value['imprintShow'] === undefined) return false;
    if (!('oidcEnabled' in value) || value['oidcEnabled'] === undefined) return false;
    if (!('privacyPolicy' in value) || value['privacyPolicy'] === undefined) return false;
    if (!('privacyPolicyShow' in value) || value['privacyPolicyShow'] === undefined) return false;
    if (!('redirectToDashboard' in value) || value['redirectToDashboard'] === undefined) return false;
    if (!('registrationEnabled' in value) || value['registrationEnabled'] === undefined) return false;
    if (!('termsOfUse' in value) || value['termsOfUse'] === undefined) return false;
    if (!('termsOfUseShow' in value) || value['termsOfUseShow'] === undefined) return false;
    return true;
}

export function SettingPageBodyFromJSON(json: any): SettingPageBody {
    return SettingPageBodyFromJSONTyped(json, false);
}

export function SettingPageBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SettingPageBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'about': json['about'],
        'aboutShow': json['about_show'],
        'contact': json['contact'],
        'contactShow': json['contact_show'],
        'emailVerificationEnabled': json['email_verification_enabled'],
        'imprint': json['imprint'],
        'imprintShow': json['imprint_show'],
        'oidcEnabled': json['oidc_enabled'],
        'privacyPolicy': json['privacy_policy'],
        'privacyPolicyShow': json['privacy_policy_show'],
        'redirectToDashboard': json['redirect_to_dashboard'],
        'registrationEnabled': json['registration_enabled'],
        'termsOfUse': json['terms_of_use'],
        'termsOfUseShow': json['terms_of_use_show'],
    };
}

export function SettingPageBodyToJSON(json: any): SettingPageBody {
    return SettingPageBodyToJSONTyped(json, false);
}

export function SettingPageBodyToJSONTyped(value?: Omit<SettingPageBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'about': value['about'],
        'about_show': value['aboutShow'],
        'contact': value['contact'],
        'contact_show': value['contactShow'],
        'email_verification_enabled': value['emailVerificationEnabled'],
        'imprint': value['imprint'],
        'imprint_show': value['imprintShow'],
        'oidc_enabled': value['oidcEnabled'],
        'privacy_policy': value['privacyPolicy'],
        'privacy_policy_show': value['privacyPolicyShow'],
        'redirect_to_dashboard': value['redirectToDashboard'],
        'registration_enabled': value['registrationEnabled'],
        'terms_of_use': value['termsOfUse'],
        'terms_of_use_show': value['termsOfUseShow'],
    };
}

