/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Shelf
 */
export interface Shelf {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof Shelf
     */
    readonly $schema?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Shelf
     */
    createdWithUserBasedPaths: boolean;
    /**
     * 
     * @type {string}
     * @memberof Shelf
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof Shelf
     */
    domain: string;
    /**
     * 
     * @type {string}
     * @memberof Shelf
     */
    footerCustomText: string;
    /**
     * 
     * @type {boolean}
     * @memberof Shelf
     */
    footerEnabled: boolean;
    /**
     * 
     * @type {string}
     * @memberof Shelf
     */
    icon: string;
    /**
     * 
     * @type {string}
     * @memberof Shelf
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof Shelf
     */
    noIndex: boolean;
    /**
     * 
     * @type {string}
     * @memberof Shelf
     */
    path: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof Shelf
     */
    theme: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof Shelf
     */
    themeId: string;
    /**
     * 
     * @type {boolean}
     * @memberof Shelf
     */
    themeMissing: boolean;
    /**
     * 
     * @type {string}
     * @memberof Shelf
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Shelf
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof Shelf
     */
    username: string;
}

/**
 * Check if a given object implements the Shelf interface.
 */
export function instanceOfShelf(value: object): value is Shelf {
    if (!('createdWithUserBasedPaths' in value) || value['createdWithUserBasedPaths'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('domain' in value) || value['domain'] === undefined) return false;
    if (!('footerCustomText' in value) || value['footerCustomText'] === undefined) return false;
    if (!('footerEnabled' in value) || value['footerEnabled'] === undefined) return false;
    if (!('icon' in value) || value['icon'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('noIndex' in value) || value['noIndex'] === undefined) return false;
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('theme' in value) || value['theme'] === undefined) return false;
    if (!('themeId' in value) || value['themeId'] === undefined) return false;
    if (!('themeMissing' in value) || value['themeMissing'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function ShelfFromJSON(json: any): Shelf {
    return ShelfFromJSONTyped(json, false);
}

export function ShelfFromJSONTyped(json: any, ignoreDiscriminator: boolean): Shelf {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'createdWithUserBasedPaths': json['createdWithUserBasedPaths'],
        'description': json['description'],
        'domain': json['domain'],
        'footerCustomText': json['footerCustomText'],
        'footerEnabled': json['footerEnabled'],
        'icon': json['icon'],
        'id': json['id'],
        'noIndex': json['noIndex'],
        'path': json['path'],
        'theme': json['theme'],
        'themeId': json['themeId'],
        'themeMissing': json['themeMissing'],
        'title': json['title'],
        'userId': json['userId'],
        'username': json['username'],
    };
}

export function ShelfToJSON(json: any): Shelf {
    return ShelfToJSONTyped(json, false);
}

export function ShelfToJSONTyped(value?: Omit<Shelf, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdWithUserBasedPaths': value['createdWithUserBasedPaths'],
        'description': value['description'],
        'domain': value['domain'],
        'footerCustomText': value['footerCustomText'],
        'footerEnabled': value['footerEnabled'],
        'icon': value['icon'],
        'id': value['id'],
        'noIndex': value['noIndex'],
        'path': value['path'],
        'theme': value['theme'],
        'themeId': value['themeId'],
        'themeMissing': value['themeMissing'],
        'title': value['title'],
        'userId': value['userId'],
        'username': value['username'],
    };
}

