/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShelfBase
 */
export interface ShelfBase {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof ShelfBase
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof ShelfBase
     */
    description?: string;
    /**
     * A fully qualified domain name with an optional port, for example profile.example.com. Stored trimmed and lowercased, without a trailing dot or slash and without :80 or :443.
     * @type {string}
     * @memberof ShelfBase
     */
    domain?: string;
    /**
     * Optional custom text shown in the footer instead of "Powered by LinkShelf", when FooterEnabled is true. Rendered as a restricted subset of Markdown: bold, italic, and links only.
     * @type {string}
     * @memberof ShelfBase
     */
    footerCustomText?: string;
    /**
     * Whether the shelf's public page shows a footer at all. Defaults to true - the shelf's public page shows the default "Powered by LinkShelf" footer, or FooterCustomText when set.
     * @type {boolean}
     * @memberof ShelfBase
     */
    footerEnabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ShelfBase
     */
    icon?: string;
    /**
     * When true, the shelf's public page asks search engines not to index it. The instance itself, and every other shelf, is unaffected.
     * @type {boolean}
     * @memberof ShelfBase
     */
    noIndex?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ShelfBase
     */
    path?: string;
    /**
     * 
     * @type {string}
     * @memberof ShelfBase
     */
    themeId?: string;
    /**
     * 
     * @type {string}
     * @memberof ShelfBase
     */
    title: string;
}

/**
 * Check if a given object implements the ShelfBase interface.
 */
export function instanceOfShelfBase(value: object): value is ShelfBase {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function ShelfBaseFromJSON(json: any): ShelfBase {
    return ShelfBaseFromJSONTyped(json, false);
}

export function ShelfBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShelfBase {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'description': json['description'] == null ? undefined : json['description'],
        'domain': json['domain'] == null ? undefined : json['domain'],
        'footerCustomText': json['footerCustomText'] == null ? undefined : json['footerCustomText'],
        'footerEnabled': json['footerEnabled'] == null ? undefined : json['footerEnabled'],
        'icon': json['icon'] == null ? undefined : json['icon'],
        'noIndex': json['noIndex'] == null ? undefined : json['noIndex'],
        'path': json['path'] == null ? undefined : json['path'],
        'themeId': json['themeId'] == null ? undefined : json['themeId'],
        'title': json['title'],
    };
}

export function ShelfBaseToJSON(json: any): ShelfBase {
    return ShelfBaseToJSONTyped(json, false);
}

export function ShelfBaseToJSONTyped(value?: Omit<ShelfBase, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'domain': value['domain'],
        'footerCustomText': value['footerCustomText'],
        'footerEnabled': value['footerEnabled'],
        'icon': value['icon'],
        'noIndex': value['noIndex'],
        'path': value['path'],
        'themeId': value['themeId'],
        'title': value['title'],
    };
}

