/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Shelf
 */
export interface Shelf {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof Shelf
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof Shelf
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof Shelf
     */
    domain: string;
    /**
     * 
     * @type {string}
     * @memberof Shelf
     */
    icon: string;
    /**
     * 
     * @type {string}
     * @memberof Shelf
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Shelf
     */
    path: string;
    /**
     * 
     * @type {string}
     * @memberof Shelf
     */
    theme: string;
    /**
     * 
     * @type {string}
     * @memberof Shelf
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Shelf
     */
    userId: string;
}

/**
 * Check if a given object implements the Shelf interface.
 */
export function instanceOfShelf(value: object): value is Shelf {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('domain' in value) || value['domain'] === undefined) return false;
    if (!('icon' in value) || value['icon'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('theme' in value) || value['theme'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function ShelfFromJSON(json: any): Shelf {
    return ShelfFromJSONTyped(json, false);
}

export function ShelfFromJSONTyped(json: any, ignoreDiscriminator: boolean): Shelf {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'description': json['description'],
        'domain': json['domain'],
        'icon': json['icon'],
        'id': json['id'],
        'path': json['path'],
        'theme': json['theme'],
        'title': json['title'],
        'userId': json['userId'],
    };
}

export function ShelfToJSON(json: any): Shelf {
    return ShelfToJSONTyped(json, false);
}

export function ShelfToJSONTyped(value?: Omit<Shelf, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'domain': value['domain'],
        'icon': value['icon'],
        'id': value['id'],
        'path': value['path'],
        'theme': value['theme'],
        'title': value['title'],
        'userId': value['userId'],
    };
}

