/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Statistic
 */
export interface Statistic {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof Statistic
     */
    readonly $schema?: string;
    /**
     * 
     * @type {number}
     * @memberof Statistic
     */
    linkNumber: number;
    /**
     * 
     * @type {number}
     * @memberof Statistic
     */
    sectionNumber: number;
    /**
     * 
     * @type {number}
     * @memberof Statistic
     */
    shelfNumber: number;
}

/**
 * Check if a given object implements the Statistic interface.
 */
export function instanceOfStatistic(value: object): value is Statistic {
    if (!('linkNumber' in value) || value['linkNumber'] === undefined) return false;
    if (!('sectionNumber' in value) || value['sectionNumber'] === undefined) return false;
    if (!('shelfNumber' in value) || value['shelfNumber'] === undefined) return false;
    return true;
}

export function StatisticFromJSON(json: any): Statistic {
    return StatisticFromJSONTyped(json, false);
}

export function StatisticFromJSONTyped(json: any, ignoreDiscriminator: boolean): Statistic {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'linkNumber': json['link_number'],
        'sectionNumber': json['section_number'],
        'shelfNumber': json['shelf_number'],
    };
}

export function StatisticToJSON(json: any): Statistic {
    return StatisticToJSONTyped(json, false);
}

export function StatisticToJSONTyped(value?: Omit<Statistic, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link_number': value['linkNumber'],
        'section_number': value['sectionNumber'],
        'shelf_number': value['shelfNumber'],
    };
}

