/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Theme } from './Theme';
import {
    ThemeFromJSON,
    ThemeFromJSONTyped,
    ThemeToJSON,
    ThemeToJSONTyped,
} from './Theme';

/**
 * 
 * @export
 * @interface ThemeGroupedResponseBody
 */
export interface ThemeGroupedResponseBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof ThemeGroupedResponseBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {Array<Theme>}
     * @memberof ThemeGroupedResponseBody
     */
    instance: Array<Theme> | null;
    /**
     * 
     * @type {Array<Theme>}
     * @memberof ThemeGroupedResponseBody
     */
    mine: Array<Theme> | null;
}

/**
 * Check if a given object implements the ThemeGroupedResponseBody interface.
 */
export function instanceOfThemeGroupedResponseBody(value: object): value is ThemeGroupedResponseBody {
    if (!('instance' in value) || value['instance'] === undefined) return false;
    if (!('mine' in value) || value['mine'] === undefined) return false;
    return true;
}

export function ThemeGroupedResponseBodyFromJSON(json: any): ThemeGroupedResponseBody {
    return ThemeGroupedResponseBodyFromJSONTyped(json, false);
}

export function ThemeGroupedResponseBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThemeGroupedResponseBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'instance': (json['instance'] == null ? null : (json['instance'] as Array<any>).map(ThemeFromJSON)),
        'mine': (json['mine'] == null ? null : (json['mine'] as Array<any>).map(ThemeFromJSON)),
    };
}

export function ThemeGroupedResponseBodyToJSON(json: any): ThemeGroupedResponseBody {
    return ThemeGroupedResponseBodyToJSONTyped(json, false);
}

export function ThemeGroupedResponseBodyToJSONTyped(value?: Omit<ThemeGroupedResponseBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'instance': (value['instance'] == null ? null : (value['instance'] as Array<any>).map(ThemeToJSON)),
        'mine': (value['mine'] == null ? null : (value['mine'] as Array<any>).map(ThemeToJSON)),
    };
}

