/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document:
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Theme
 */
export interface Theme {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof Theme
     */
    readonly $schema?: string;
    /**
     *
     * @type {string}
     * @memberof Theme
     */
    config: string;
    /**
     *
     * @type {string}
     * @memberof Theme
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof Theme
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof Theme
     */
    ownerUserId?: string;
    /**
     *
     * @type {string}
     * @memberof Theme
     */
    scope: string;
    /**
     *
     * @type {string}
     * @memberof Theme
     */
    sourceFile?: string;
}

/**
 * Check if a given object implements the Theme interface.
 */
export function instanceOfTheme(value: object): value is Theme {
    if (!('config' in value) || value['config'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('scope' in value) || value['scope'] === undefined) return false;
    return true;
}

export function ThemeFromJSON(json: any): Theme {
    return ThemeFromJSONTyped(json, false);
}

export function ThemeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Theme {
    if (json == null) {
        return json;
    }
    return {

        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'config': json['config'],
        'id': json['id'],
        'name': json['name'],
        'ownerUserId': json['ownerUserId'] == null ? undefined : json['ownerUserId'],
        'scope': json['scope'],
        'sourceFile': json['sourceFile'] == null ? undefined : json['sourceFile'],
    };
}

export function ThemeToJSON(json: any): Theme {
    return ThemeToJSONTyped(json, false);
}

export function ThemeToJSONTyped(value?: Omit<Theme, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'config': value['config'],
        'id': value['id'],
        'name': value['name'],
        'ownerUserId': value['ownerUserId'],
        'scope': value['scope'],
        'sourceFile': value['sourceFile'],
    };
}

