/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ThemeBase
 */
export interface ThemeBase {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof ThemeBase
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeBase
     */
    config: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeBase
     */
    name: string;
}

/**
 * Check if a given object implements the ThemeBase interface.
 */
export function instanceOfThemeBase(value: object): value is ThemeBase {
    if (!('config' in value) || value['config'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ThemeBaseFromJSON(json: any): ThemeBase {
    return ThemeBaseFromJSONTyped(json, false);
}

export function ThemeBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThemeBase {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'config': json['config'],
        'name': json['name'],
    };
}

export function ThemeBaseToJSON(json: any): ThemeBase {
    return ThemeBaseToJSONTyped(json, false);
}

export function ThemeBaseToJSONTyped(value?: Omit<ThemeBase, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': value['config'],
        'name': value['name'],
    };
}

