/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenPair
 */
export interface TokenPair {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof TokenPair
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof TokenPair
     */
    accessToken: string;
    /**
     * 
     * @type {string}
     * @memberof TokenPair
     */
    refreshToken: string;
}

/**
 * Check if a given object implements the TokenPair interface.
 */
export function instanceOfTokenPair(value: object): value is TokenPair {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    return true;
}

export function TokenPairFromJSON(json: any): TokenPair {
    return TokenPairFromJSONTyped(json, false);
}

export function TokenPairFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenPair {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'accessToken': json['access_token'],
        'refreshToken': json['refresh_token'],
    };
}

export function TokenPairToJSON(json: any): TokenPair {
    return TokenPairToJSONTyped(json, false);
}

export function TokenPairToJSONTyped(value?: Omit<TokenPair, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_token': value['accessToken'],
        'refresh_token': value['refreshToken'],
    };
}

