/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserBase
 */
export interface UserBase {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof UserBase
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof UserBase
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserBase
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof UserBase
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof UserBase
     */
    password: string;
}

/**
 * Check if a given object implements the UserBase interface.
 */
export function instanceOfUserBase(value: object): value is UserBase {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function UserBaseFromJSON(json: any): UserBase {
    return UserBaseFromJSONTyped(json, false);
}

export function UserBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserBase {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'email': json['email'],
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'password': json['password'],
    };
}

export function UserBaseToJSON(json: any): UserBase {
    return UserBaseToJSONTyped(json, false);
}

export function UserBaseToJSONTyped(value?: Omit<UserBase, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'password': value['password'],
    };
}

