/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserLimitsPatch
 */
export interface UserLimitsPatch {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof UserLimitsPatch
     */
    readonly $schema?: string;
    /**
     * Shelf limit, zero or more. null for unlimited.
     * @type {number}
     * @memberof UserLimitsPatch
     */
    maxShelves: number | null;
}

/**
 * Check if a given object implements the UserLimitsPatch interface.
 */
export function instanceOfUserLimitsPatch(value: object): value is UserLimitsPatch {
    if (!('maxShelves' in value) || value['maxShelves'] === undefined) return false;
    return true;
}

export function UserLimitsPatchFromJSON(json: any): UserLimitsPatch {
    return UserLimitsPatchFromJSONTyped(json, false);
}

export function UserLimitsPatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserLimitsPatch {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'maxShelves': json['max_shelves'],
    };
}

export function UserLimitsPatchToJSON(json: any): UserLimitsPatch {
    return UserLimitsPatchToJSONTyped(json, false);
}

export function UserLimitsPatchToJSONTyped(value?: Omit<UserLimitsPatch, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'max_shelves': value['maxShelves'],
    };
}

