/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserLimits
 */
export interface UserLimits {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof UserLimits
     */
    readonly $schema?: string;
    /**
     * Shelf limit, null for unlimited.
     * @type {number}
     * @memberof UserLimits
     */
    maxShelves: number | null;
    /**
     * 
     * @type {number}
     * @memberof UserLimits
     */
    shelfCount: number;
}

/**
 * Check if a given object implements the UserLimits interface.
 */
export function instanceOfUserLimits(value: object): value is UserLimits {
    if (!('maxShelves' in value) || value['maxShelves'] === undefined) return false;
    if (!('shelfCount' in value) || value['shelfCount'] === undefined) return false;
    return true;
}

export function UserLimitsFromJSON(json: any): UserLimits {
    return UserLimitsFromJSONTyped(json, false);
}

export function UserLimitsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserLimits {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'maxShelves': json['max_shelves'],
        'shelfCount': json['shelf_count'],
    };
}

export function UserLimitsToJSON(json: any): UserLimits {
    return UserLimitsToJSONTyped(json, false);
}

export function UserLimitsToJSONTyped(value?: Omit<UserLimits, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'max_shelves': value['maxShelves'],
        'shelf_count': value['shelfCount'],
    };
}

