/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserRequestBodyOnlyPassword
 */
export interface UserRequestBodyOnlyPassword {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof UserRequestBodyOnlyPassword
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof UserRequestBodyOnlyPassword
     */
    newPassword: string;
    /**
     * 
     * @type {string}
     * @memberof UserRequestBodyOnlyPassword
     */
    oldPassword: string;
}

/**
 * Check if a given object implements the UserRequestBodyOnlyPassword interface.
 */
export function instanceOfUserRequestBodyOnlyPassword(value: object): value is UserRequestBodyOnlyPassword {
    if (!('newPassword' in value) || value['newPassword'] === undefined) return false;
    if (!('oldPassword' in value) || value['oldPassword'] === undefined) return false;
    return true;
}

export function UserRequestBodyOnlyPasswordFromJSON(json: any): UserRequestBodyOnlyPassword {
    return UserRequestBodyOnlyPasswordFromJSONTyped(json, false);
}

export function UserRequestBodyOnlyPasswordFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRequestBodyOnlyPassword {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'newPassword': json['new_password'],
        'oldPassword': json['old_password'],
    };
}

export function UserRequestBodyOnlyPasswordToJSON(json: any): UserRequestBodyOnlyPassword {
    return UserRequestBodyOnlyPasswordToJSONTyped(json, false);
}

export function UserRequestBodyOnlyPasswordToJSONTyped(value?: Omit<UserRequestBodyOnlyPassword, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'new_password': value['newPassword'],
        'old_password': value['oldPassword'],
    };
}

