/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyEmailRequest
 */
export interface VerifyEmailRequest {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof VerifyEmailRequest
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyEmailRequest
     */
    token: string;
}

/**
 * Check if a given object implements the VerifyEmailRequest interface.
 */
export function instanceOfVerifyEmailRequest(value: object): value is VerifyEmailRequest {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function VerifyEmailRequestFromJSON(json: any): VerifyEmailRequest {
    return VerifyEmailRequestFromJSONTyped(json, false);
}

export function VerifyEmailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyEmailRequest {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'token': json['token'],
    };
}

export function VerifyEmailRequestToJSON(json: any): VerifyEmailRequest {
    return VerifyEmailRequestToJSONTyped(json, false);
}

export function VerifyEmailRequestToJSONTyped(value?: Omit<VerifyEmailRequest, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

