services:
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - "15432:5432"
    shm_size: 128mb
    environment:
      POSTGRES_USER: linkshelf
      POSTGRES_PASSWORD: linkshelf
      POSTGRES_DB: linkshelf
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U linkshelf -d linkshelf" ]
      interval: 2s
      timeout: 3s
      retries: 30

  mysql:
    image: mysql:26.7.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=linkshelf
      - MYSQL_DATABASE=linkshelf
      - MYSQL_USER=linkshelf
      - MYSQL_PASSWORD=linkshelf

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8086:8080"