// Code generated by MockGen. DO NOT EDIT.
// Source: email_verification.go
//
// Generated by this command:
//
//	mockgen -source=email_verification.go -destination=mocks/email_verification_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	model "backend/internal/infrastructure/api/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEmailVerificationService is a mock of EmailVerificationService interface.
type MockEmailVerificationService struct {
	ctrl     *gomock.Controller
	recorder *MockEmailVerificationServiceMockRecorder
	isgomock struct{}
}

// MockEmailVerificationServiceMockRecorder is the mock recorder for MockEmailVerificationService.
type MockEmailVerificationServiceMockRecorder struct {
	mock *MockEmailVerificationService
}

// NewMockEmailVerificationService creates a new mock instance.
func NewMockEmailVerificationService(ctrl *gomock.Controller) *MockEmailVerificationService {
	mock := &MockEmailVerificationService{ctrl: ctrl}
	mock.recorder = &MockEmailVerificationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailVerificationService) EXPECT() *MockEmailVerificationServiceMockRecorder {
	return m.recorder
}

// ConfirmEmailChange mocks base method.
func (m *MockEmailVerificationService) ConfirmEmailChange(rawToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmEmailChange", rawToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmEmailChange indicates an expected call of ConfirmEmailChange.
func (mr *MockEmailVerificationServiceMockRecorder) ConfirmEmailChange(rawToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmEmailChange", reflect.TypeOf((*MockEmailVerificationService)(nil).ConfirmEmailChange), rawToken)
}

// MarkVerified mocks base method.
func (m *MockEmailVerificationService) MarkVerified(userId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkVerified", userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkVerified indicates an expected call of MarkVerified.
func (mr *MockEmailVerificationServiceMockRecorder) MarkVerified(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkVerified", reflect.TypeOf((*MockEmailVerificationService)(nil).MarkVerified), userId)
}

// NotifyProviderLinked mocks base method.
func (m *MockEmailVerificationService) NotifyProviderLinked(email string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotifyProviderLinked", email)
}

// NotifyProviderLinked indicates an expected call of NotifyProviderLinked.
func (mr *MockEmailVerificationServiceMockRecorder) NotifyProviderLinked(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyProviderLinked", reflect.TypeOf((*MockEmailVerificationService)(nil).NotifyProviderLinked), email)
}

// RequestEmailChange mocks base method.
func (m *MockEmailVerificationService) RequestEmailChange(userId, currentEmail, newEmail string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestEmailChange", userId, currentEmail, newEmail)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestEmailChange indicates an expected call of RequestEmailChange.
func (mr *MockEmailVerificationServiceMockRecorder) RequestEmailChange(userId, currentEmail, newEmail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestEmailChange", reflect.TypeOf((*MockEmailVerificationService)(nil).RequestEmailChange), userId, currentEmail, newEmail)
}

// RequestPasswordReset mocks base method.
func (m *MockEmailVerificationService) RequestPasswordReset(email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestPasswordReset", email)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequestPasswordReset indicates an expected call of RequestPasswordReset.
func (mr *MockEmailVerificationServiceMockRecorder) RequestPasswordReset(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestPasswordReset", reflect.TypeOf((*MockEmailVerificationService)(nil).RequestPasswordReset), email)
}

// Resend mocks base method.
func (m *MockEmailVerificationService) Resend(email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resend", email)
	ret0, _ := ret[0].(error)
	return ret0
}

// Resend indicates an expected call of Resend.
func (mr *MockEmailVerificationServiceMockRecorder) Resend(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resend", reflect.TypeOf((*MockEmailVerificationService)(nil).Resend), email)
}

// ResetPassword mocks base method.
func (m *MockEmailVerificationService) ResetPassword(rawToken, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetPassword", rawToken, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetPassword indicates an expected call of ResetPassword.
func (mr *MockEmailVerificationServiceMockRecorder) ResetPassword(rawToken, newPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetPassword", reflect.TypeOf((*MockEmailVerificationService)(nil).ResetPassword), rawToken, newPassword)
}

// SendInitial mocks base method.
func (m *MockEmailVerificationService) SendInitial(user *model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendInitial", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendInitial indicates an expected call of SendInitial.
func (mr *MockEmailVerificationServiceMockRecorder) SendInitial(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendInitial", reflect.TypeOf((*MockEmailVerificationService)(nil).SendInitial), user)
}

// SetPassword mocks base method.
func (m *MockEmailVerificationService) SetPassword(rawToken, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPassword", rawToken, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPassword indicates an expected call of SetPassword.
func (mr *MockEmailVerificationServiceMockRecorder) SetPassword(rawToken, newPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPassword", reflect.TypeOf((*MockEmailVerificationService)(nil).SetPassword), rawToken, newPassword)
}

// VerifyEmail mocks base method.
func (m *MockEmailVerificationService) VerifyEmail(rawToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyEmail", rawToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyEmail indicates an expected call of VerifyEmail.
func (mr *MockEmailVerificationServiceMockRecorder) VerifyEmail(rawToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyEmail", reflect.TypeOf((*MockEmailVerificationService)(nil).VerifyEmail), rawToken)
}
