// Code generated by MockGen. DO NOT EDIT.
// Source: section.go
//
// Generated by this command:
//
//	mockgen -source=section.go -destination=mocks/section_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	model "backend/internal/infrastructure/api/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSectionService is a mock of SectionService interface.
type MockSectionService struct {
	ctrl     *gomock.Controller
	recorder *MockSectionServiceMockRecorder
	isgomock struct{}
}

// MockSectionServiceMockRecorder is the mock recorder for MockSectionService.
type MockSectionServiceMockRecorder struct {
	mock *MockSectionService
}

// NewMockSectionService creates a new mock instance.
func NewMockSectionService(ctrl *gomock.Controller) *MockSectionService {
	mock := &MockSectionService{ctrl: ctrl}
	mock.recorder = &MockSectionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSectionService) EXPECT() *MockSectionServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSectionService) Create(u *model.Section) (*model.Section, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", u)
	ret0, _ := ret[0].(*model.Section)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSectionServiceMockRecorder) Create(u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSectionService)(nil).Create), u)
}

// Delete mocks base method.
func (m *MockSectionService) Delete(sectionId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", sectionId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSectionServiceMockRecorder) Delete(sectionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSectionService)(nil).Delete), sectionId)
}

// Get mocks base method.
func (m *MockSectionService) Get(sectionId string) (*model.Section, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", sectionId)
	ret0, _ := ret[0].(*model.Section)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSectionServiceMockRecorder) Get(sectionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSectionService)(nil).Get), sectionId)
}

// List mocks base method.
func (m *MockSectionService) List(shelfId string) ([]model.Section, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", shelfId)
	ret0, _ := ret[0].([]model.Section)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSectionServiceMockRecorder) List(shelfId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSectionService)(nil).List), shelfId)
}

// Update mocks base method.
func (m *MockSectionService) Update(sectionId string, u *model.Section) (*model.Section, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", sectionId, u)
	ret0, _ := ret[0].(*model.Section)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSectionServiceMockRecorder) Update(sectionId, u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSectionService)(nil).Update), sectionId, u)
}
