// Code generated by MockGen. DO NOT EDIT.
// Source: setting.go
//
// Generated by this command:
//
//	mockgen -source=setting.go -destination=mocks/setting_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	model "backend/internal/infrastructure/api/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSettingService is a mock of SettingService interface.
type MockSettingService struct {
	ctrl     *gomock.Controller
	recorder *MockSettingServiceMockRecorder
	isgomock struct{}
}

// MockSettingServiceMockRecorder is the mock recorder for MockSettingService.
type MockSettingServiceMockRecorder struct {
	mock *MockSettingService
}

// NewMockSettingService creates a new mock instance.
func NewMockSettingService(ctrl *gomock.Controller) *MockSettingService {
	mock := &MockSettingService{ctrl: ctrl}
	mock.recorder = &MockSettingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettingService) EXPECT() *MockSettingServiceMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockSettingService) List() ([]model.Setting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]model.Setting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSettingServiceMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSettingService)(nil).List))
}

// Update mocks base method.
func (m *MockSettingService) Update(setting model.Setting) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", setting)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSettingServiceMockRecorder) Update(setting any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSettingService)(nil).Update), setting)
}
