// Code generated by MockGen. DO NOT EDIT.
// Source: shelf.go
//
// Generated by this command:
//
//	mockgen -source=shelf.go -destination=mocks/shelf_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	model "backend/internal/infrastructure/api/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockShelfService is a mock of ShelfService interface.
type MockShelfService struct {
	ctrl     *gomock.Controller
	recorder *MockShelfServiceMockRecorder
	isgomock struct{}
}

// MockShelfServiceMockRecorder is the mock recorder for MockShelfService.
type MockShelfServiceMockRecorder struct {
	mock *MockShelfService
}

// NewMockShelfService creates a new mock instance.
func NewMockShelfService(ctrl *gomock.Controller) *MockShelfService {
	mock := &MockShelfService{ctrl: ctrl}
	mock.recorder = &MockShelfServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShelfService) EXPECT() *MockShelfServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockShelfService) Create(u *model.Shelf) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", u)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockShelfServiceMockRecorder) Create(u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockShelfService)(nil).Create), u)
}

// Delete mocks base method.
func (m *MockShelfService) Delete(u *model.Shelf) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", u)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockShelfServiceMockRecorder) Delete(u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockShelfService)(nil).Delete), u)
}

// Get mocks base method.
func (m *MockShelfService) Get(id string) (*model.Shelf, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(*model.Shelf)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockShelfServiceMockRecorder) Get(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockShelfService)(nil).Get), id)
}

// Update mocks base method.
func (m *MockShelfService) Update(shelfId string, shelfRequest *model.Shelf) (*model.Shelf, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", shelfId, shelfRequest)
	ret0, _ := ret[0].(*model.Shelf)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockShelfServiceMockRecorder) Update(shelfId, shelfRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockShelfService)(nil).Update), shelfId, shelfRequest)
}
