// Code generated by MockGen. DO NOT EDIT.
// Source: statistic.go
//
// Generated by this command:
//
//	mockgen -source=statistic.go -destination=mocks/statistic_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	model "backend/internal/infrastructure/api/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStatisticService is a mock of StatisticService interface.
type MockStatisticService struct {
	ctrl     *gomock.Controller
	recorder *MockStatisticServiceMockRecorder
	isgomock struct{}
}

// MockStatisticServiceMockRecorder is the mock recorder for MockStatisticService.
type MockStatisticServiceMockRecorder struct {
	mock *MockStatisticService
}

// NewMockStatisticService creates a new mock instance.
func NewMockStatisticService(ctrl *gomock.Controller) *MockStatisticService {
	mock := &MockStatisticService{ctrl: ctrl}
	mock.recorder = &MockStatisticServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatisticService) EXPECT() *MockStatisticServiceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockStatisticService) Get(userId string) (*model.Statistic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", userId)
	ret0, _ := ret[0].(*model.Statistic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStatisticServiceMockRecorder) Get(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStatisticService)(nil).Get), userId)
}
