// Code generated by MockGen. DO NOT EDIT.
// Source: theme.go
//
// Generated by this command:
//
//	mockgen -source=theme.go -destination=mocks/theme_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	model "backend/internal/infrastructure/api/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockThemeService is a mock of ThemeService interface.
type MockThemeService struct {
	ctrl     *gomock.Controller
	recorder *MockThemeServiceMockRecorder
	isgomock struct{}
}

// MockThemeServiceMockRecorder is the mock recorder for MockThemeService.
type MockThemeServiceMockRecorder struct {
	mock *MockThemeService
}

// NewMockThemeService creates a new mock instance.
func NewMockThemeService(ctrl *gomock.Controller) *MockThemeService {
	mock := &MockThemeService{ctrl: ctrl}
	mock.recorder = &MockThemeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockThemeService) EXPECT() *MockThemeServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockThemeService) Create(callerUserId string, base model.ThemeBase) (*model.Theme, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", callerUserId, base)
	ret0, _ := ret[0].(*model.Theme)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockThemeServiceMockRecorder) Create(callerUserId, base any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockThemeService)(nil).Create), callerUserId, base)
}

// Delete mocks base method.
func (m *MockThemeService) Delete(themeId, callerUserId string, isAdmin bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", themeId, callerUserId, isAdmin)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockThemeServiceMockRecorder) Delete(themeId, callerUserId, isAdmin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockThemeService)(nil).Delete), themeId, callerUserId, isAdmin)
}

// Get mocks base method.
func (m *MockThemeService) Get(themeId, callerUserId string, isAdmin bool) (*model.Theme, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", themeId, callerUserId, isAdmin)
	ret0, _ := ret[0].(*model.Theme)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockThemeServiceMockRecorder) Get(themeId, callerUserId, isAdmin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockThemeService)(nil).Get), themeId, callerUserId, isAdmin)
}

// ListAllUserScoped mocks base method.
func (m *MockThemeService) ListAllUserScoped() ([]model.Theme, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllUserScoped")
	ret0, _ := ret[0].([]model.Theme)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllUserScoped indicates an expected call of ListAllUserScoped.
func (mr *MockThemeServiceMockRecorder) ListAllUserScoped() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllUserScoped", reflect.TypeOf((*MockThemeService)(nil).ListAllUserScoped))
}

// ListGrouped mocks base method.
func (m *MockThemeService) ListGrouped(callerUserId string) (model.ThemeGroupedResponseBody, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGrouped", callerUserId)
	ret0, _ := ret[0].(model.ThemeGroupedResponseBody)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGrouped indicates an expected call of ListGrouped.
func (mr *MockThemeServiceMockRecorder) ListGrouped(callerUserId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGrouped", reflect.TypeOf((*MockThemeService)(nil).ListGrouped), callerUserId)
}

// Resolve mocks base method.
func (m *MockThemeService) Resolve(themeId string) (map[string]string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", themeId)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Resolve indicates an expected call of Resolve.
func (mr *MockThemeServiceMockRecorder) Resolve(themeId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockThemeService)(nil).Resolve), themeId)
}

// Update mocks base method.
func (m *MockThemeService) Update(themeId, callerUserId string, base model.ThemeBase) (*model.Theme, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", themeId, callerUserId, base)
	ret0, _ := ret[0].(*model.Theme)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockThemeServiceMockRecorder) Update(themeId, callerUserId, base any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockThemeService)(nil).Update), themeId, callerUserId, base)
}

// ValidateAssignable mocks base method.
func (m *MockThemeService) ValidateAssignable(themeId, shelfOwnerUserId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAssignable", themeId, shelfOwnerUserId)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateAssignable indicates an expected call of ValidateAssignable.
func (mr *MockThemeServiceMockRecorder) ValidateAssignable(themeId, shelfOwnerUserId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAssignable", reflect.TypeOf((*MockThemeService)(nil).ValidateAssignable), themeId, shelfOwnerUserId)
}
