// Code generated by MockGen. DO NOT EDIT.
// Source: user.go
//
// Generated by this command:
//
//	mockgen -source=user.go -destination=mocks/user_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	model "backend/internal/infrastructure/api/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
	isgomock struct{}
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserService) Create(u *model.UserCreate, callerIsAdmin bool) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", u, callerIsAdmin)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserServiceMockRecorder) Create(u, callerIsAdmin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserService)(nil).Create), u, callerIsAdmin)
}

// Delete mocks base method.
func (m *MockUserService) Delete(u *model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", u)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserServiceMockRecorder) Delete(u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserService)(nil).Delete), u)
}

// Get mocks base method.
func (m *MockUserService) Get(id string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUserServiceMockRecorder) Get(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUserService)(nil).Get), id)
}

// GetLimits mocks base method.
func (m *MockUserService) GetLimits(userId string) (*model.UserLimits, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLimits", userId)
	ret0, _ := ret[0].(*model.UserLimits)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLimits indicates an expected call of GetLimits.
func (mr *MockUserServiceMockRecorder) GetLimits(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLimits", reflect.TypeOf((*MockUserService)(nil).GetLimits), userId)
}

// List mocks base method.
func (m *MockUserService) List() ([]model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockUserServiceMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUserService)(nil).List))
}

// PatchPassword mocks base method.
func (m *MockUserService) PatchPassword(userId string, u *model.UserRequestBodyOnlyPassword) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchPassword", userId, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// PatchPassword indicates an expected call of PatchPassword.
func (mr *MockUserServiceMockRecorder) PatchPassword(userId, u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchPassword", reflect.TypeOf((*MockUserService)(nil).PatchPassword), userId, u)
}

// SetMaxShelves mocks base method.
func (m *MockUserService) SetMaxShelves(userId string, maxShelves *int) (*model.UserLimits, *int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMaxShelves", userId, maxShelves)
	ret0, _ := ret[0].(*model.UserLimits)
	ret1, _ := ret[1].(*int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SetMaxShelves indicates an expected call of SetMaxShelves.
func (mr *MockUserServiceMockRecorder) SetMaxShelves(userId, maxShelves any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMaxShelves", reflect.TypeOf((*MockUserService)(nil).SetMaxShelves), userId, maxShelves)
}

// Update mocks base method.
func (m *MockUserService) Update(userId string, userRequest *model.User, callerIsAdmin bool) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", userId, userRequest, callerIsAdmin)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockUserServiceMockRecorder) Update(userId, userRequest, callerIsAdmin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserService)(nil).Update), userId, userRequest, callerIsAdmin)
}
