apiVersion: v1
kind: Service
metadata:
  name: {{ include "linkshelf.fullname" . }}
  labels:
    {{- include "linkshelf.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: frontend
      port: {{ .Values.service.frontendPort }}
      targetPort: frontend
    - name: backend
      port: {{ .Values.service.backendPort }}
      targetPort: backend
  selector:
    {{- include "linkshelf.selectorLabels" . | nindent 4 }}
