/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorModel,
  LoginRequest,
  OidcCallbackRequest,
  OidcLoginResponseBody,
  RefreshRequest,
  TokenPair,
} from '../models/index';
import {
    ErrorModelFromJSON,
    ErrorModelToJSON,
    LoginRequestFromJSON,
    LoginRequestToJSON,
    OidcCallbackRequestFromJSON,
    OidcCallbackRequestToJSON,
    OidcLoginResponseBodyFromJSON,
    OidcLoginResponseBodyToJSON,
    RefreshRequestFromJSON,
    RefreshRequestToJSON,
    TokenPairFromJSON,
    TokenPairToJSON,
} from '../models/index';

export interface PostLoginRequest {
    loginRequest: Omit<LoginRequest, '$schema'>;
}

export interface PostLogoutRequest {
    refreshRequest: Omit<RefreshRequest, '$schema'>;
}

export interface PostOidcCallbackRequest {
    oidcCallbackRequest: Omit<OidcCallbackRequest, '$schema'>;
    authorization?: string;
}

export interface PostRefreshRequest {
    refreshRequest: Omit<RefreshRequest, '$schema'>;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * Returns the authorization URL (PKCE-protected) the frontend should redirect the browser to, and the state to send back to the callback.
     * Start OIDC login
     */
    async getOidcLoginRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OidcLoginResponseBody>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/auth/oidc/login`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OidcLoginResponseBodyFromJSON(jsonValue));
    }

    /**
     * Returns the authorization URL (PKCE-protected) the frontend should redirect the browser to, and the state to send back to the callback.
     * Start OIDC login
     */
    async getOidcLogin(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OidcLoginResponseBody> {
        const response = await this.getOidcLoginRaw(initOverrides);
        return await response.value();
    }

    /**
     * Log in with a local username and password, returning an access/refresh token pair.
     * Login
     */
    async postLoginRaw(requestParameters: PostLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenPair>> {
        if (requestParameters['loginRequest'] == null) {
            throw new runtime.RequiredError(
                'loginRequest',
                'Required parameter "loginRequest" was null or undefined when calling postLogin().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/auth/login`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginRequestToJSON(requestParameters['loginRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenPairFromJSON(jsonValue));
    }

    /**
     * Log in with a local username and password, returning an access/refresh token pair.
     * Login
     */
    async postLogin(requestParameters: PostLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenPair> {
        const response = await this.postLoginRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Invalidate a refresh token. The current access token simply expires on its own shortly after.
     * Logout
     */
    async postLogoutRaw(requestParameters: PostLogoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['refreshRequest'] == null) {
            throw new runtime.RequiredError(
                'refreshRequest',
                'Required parameter "refreshRequest" was null or undefined when calling postLogout().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/auth/logout`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RefreshRequestToJSON(requestParameters['refreshRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Invalidate a refresh token. The current access token simply expires on its own shortly after.
     * Logout
     */
    async postLogout(requestParameters: PostLogoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.postLogoutRaw(requestParameters, initOverrides);
    }

    /**
     * Exchanges an authorization code for tokens. Behaves as login-or-auto-provision when called anonymously, or as link-to-my-account when called with a valid Bearer token.
     * Complete OIDC login
     */
    async postOidcCallbackRaw(requestParameters: PostOidcCallbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenPair>> {
        if (requestParameters['oidcCallbackRequest'] == null) {
            throw new runtime.RequiredError(
                'oidcCallbackRequest',
                'Required parameter "oidcCallbackRequest" was null or undefined when calling postOidcCallback().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v1/auth/oidc/callback`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OidcCallbackRequestToJSON(requestParameters['oidcCallbackRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenPairFromJSON(jsonValue));
    }

    /**
     * Exchanges an authorization code for tokens. Behaves as login-or-auto-provision when called anonymously, or as link-to-my-account when called with a valid Bearer token.
     * Complete OIDC login
     */
    async postOidcCallback(requestParameters: PostOidcCallbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenPair> {
        const response = await this.postOidcCallbackRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Exchange a refresh token for a new access/refresh token pair. The refresh token used is invalidated (single-use rotation).
     * Refresh token
     */
    async postRefreshRaw(requestParameters: PostRefreshRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenPair>> {
        if (requestParameters['refreshRequest'] == null) {
            throw new runtime.RequiredError(
                'refreshRequest',
                'Required parameter "refreshRequest" was null or undefined when calling postRefresh().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/auth/refresh`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RefreshRequestToJSON(requestParameters['refreshRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenPairFromJSON(jsonValue));
    }

    /**
     * Exchange a refresh token for a new access/refresh token pair. The refresh token used is invalidated (single-use rotation).
     * Refresh token
     */
    async postRefresh(requestParameters: PostRefreshRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenPair> {
        const response = await this.postRefreshRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
