/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorModel,
  Link,
  LinkBase,
} from '../models/index';
import {
    ErrorModelFromJSON,
    ErrorModelToJSON,
    LinkFromJSON,
    LinkToJSON,
    LinkBaseFromJSON,
    LinkBaseToJSON,
} from '../models/index';

export interface DeleteLinkRequest {
    linkId: string;
    shelfId?: string;
}

export interface GetLinksRequest {
    shelfId?: string;
}

export interface PostCreateLinkRequest {
    linkBase: Omit<LinkBase, '$schema'>;
}

export interface PutUpdateLinkRequest {
    linkId: string;
    linkBase: Omit<LinkBase, '$schema'>;
    shelfId?: string;
}

/**
 * 
 */
export class LinkApi extends runtime.BaseAPI {

    /**
     * Delete a link by ID.
     * Delete link
     */
    async deleteLinkRaw(requestParameters: DeleteLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['linkId'] == null) {
            throw new runtime.RequiredError(
                'linkId',
                'Required parameter "linkId" was null or undefined when calling deleteLink().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['shelfId'] != null) {
            queryParameters['shelfId'] = requestParameters['shelfId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/links/{linkId}`;
        urlPath = urlPath.replace(`{${"linkId"}}`, encodeURIComponent(String(requestParameters['linkId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a link by ID.
     * Delete link
     */
    async deleteLink(requestParameters: DeleteLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteLinkRaw(requestParameters, initOverrides);
    }

    /**
     * Get links by shelf ID.
     * Get links by shelf ID
     */
    async getLinksRaw(requestParameters: GetLinksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Link>>> {
        const queryParameters: any = {};

        if (requestParameters['shelfId'] != null) {
            queryParameters['shelfId'] = requestParameters['shelfId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/links`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LinkFromJSON));
    }

    /**
     * Get links by shelf ID.
     * Get links by shelf ID
     */
    async getLinks(requestParameters: GetLinksRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Link>> {
        const response = await this.getLinksRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new link.
     * Create link
     */
    async postCreateLinkRaw(requestParameters: PostCreateLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Link>> {
        if (requestParameters['linkBase'] == null) {
            throw new runtime.RequiredError(
                'linkBase',
                'Required parameter "linkBase" was null or undefined when calling postCreateLink().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/links`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LinkBaseToJSON(requestParameters['linkBase']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LinkFromJSON(jsonValue));
    }

    /**
     * Create a new link.
     * Create link
     */
    async postCreateLink(requestParameters: PostCreateLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Link> {
        const response = await this.postCreateLinkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an existing link.
     * Update link
     */
    async putUpdateLinkRaw(requestParameters: PutUpdateLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Link>> {
        if (requestParameters['linkId'] == null) {
            throw new runtime.RequiredError(
                'linkId',
                'Required parameter "linkId" was null or undefined when calling putUpdateLink().'
            );
        }

        if (requestParameters['linkBase'] == null) {
            throw new runtime.RequiredError(
                'linkBase',
                'Required parameter "linkBase" was null or undefined when calling putUpdateLink().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['shelfId'] != null) {
            queryParameters['shelfId'] = requestParameters['shelfId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/links/{linkId}`;
        urlPath = urlPath.replace(`{${"linkId"}}`, encodeURIComponent(String(requestParameters['linkId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: LinkBaseToJSON(requestParameters['linkBase']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LinkFromJSON(jsonValue));
    }

    /**
     * Update an existing link.
     * Update link
     */
    async putUpdateLink(requestParameters: PutUpdateLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Link> {
        const response = await this.putUpdateLinkRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
