/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorModel,
  Section,
  SectionBase,
} from '../models/index';
import {
    ErrorModelFromJSON,
    ErrorModelToJSON,
    SectionFromJSON,
    SectionToJSON,
    SectionBaseFromJSON,
    SectionBaseToJSON,
} from '../models/index';

export interface DeleteSectionRequest {
    sectionId: string;
}

export interface GetSectionsRequest {
    shelfId?: string;
}

export interface PostCreateSectionRequest {
    sectionBase: Omit<SectionBase, '$schema'>;
}

export interface PutUpdateSectionRequest {
    sectionId: string;
    sectionBase: Omit<SectionBase, '$schema'>;
}

/**
 * 
 */
export class SectionApi extends runtime.BaseAPI {

    /**
     * Delete a section by ID.
     * Delete section
     */
    async deleteSectionRaw(requestParameters: DeleteSectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['sectionId'] == null) {
            throw new runtime.RequiredError(
                'sectionId',
                'Required parameter "sectionId" was null or undefined when calling deleteSection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/sections/{sectionId}`;
        urlPath = urlPath.replace(`{${"sectionId"}}`, encodeURIComponent(String(requestParameters['sectionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a section by ID.
     * Delete section
     */
    async deleteSection(requestParameters: DeleteSectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteSectionRaw(requestParameters, initOverrides);
    }

    /**
     * Get sections by shelf ID.
     * Get sections by shelf ID
     */
    async getSectionsRaw(requestParameters: GetSectionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Section>>> {
        const queryParameters: any = {};

        if (requestParameters['shelfId'] != null) {
            queryParameters['shelfId'] = requestParameters['shelfId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/sections`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SectionFromJSON));
    }

    /**
     * Get sections by shelf ID.
     * Get sections by shelf ID
     */
    async getSections(requestParameters: GetSectionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Section>> {
        const response = await this.getSectionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new section.
     * Create section
     */
    async postCreateSectionRaw(requestParameters: PostCreateSectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Section>> {
        if (requestParameters['sectionBase'] == null) {
            throw new runtime.RequiredError(
                'sectionBase',
                'Required parameter "sectionBase" was null or undefined when calling postCreateSection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/sections`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SectionBaseToJSON(requestParameters['sectionBase']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SectionFromJSON(jsonValue));
    }

    /**
     * Create a new section.
     * Create section
     */
    async postCreateSection(requestParameters: PostCreateSectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Section> {
        const response = await this.postCreateSectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an existing section.
     * Update section
     */
    async putUpdateSectionRaw(requestParameters: PutUpdateSectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Section>> {
        if (requestParameters['sectionId'] == null) {
            throw new runtime.RequiredError(
                'sectionId',
                'Required parameter "sectionId" was null or undefined when calling putUpdateSection().'
            );
        }

        if (requestParameters['sectionBase'] == null) {
            throw new runtime.RequiredError(
                'sectionBase',
                'Required parameter "sectionBase" was null or undefined when calling putUpdateSection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/sections/{sectionId}`;
        urlPath = urlPath.replace(`{${"sectionId"}}`, encodeURIComponent(String(requestParameters['sectionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SectionBaseToJSON(requestParameters['sectionBase']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SectionFromJSON(jsonValue));
    }

    /**
     * Update an existing section.
     * Update section
     */
    async putUpdateSection(requestParameters: PutUpdateSectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Section> {
        const response = await this.putUpdateSectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
