/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorModel,
  Setting,
  SettingPageBody,
} from '../models/index';
import {
    ErrorModelFromJSON,
    ErrorModelToJSON,
    SettingFromJSON,
    SettingToJSON,
    SettingPageBodyFromJSON,
    SettingPageBodyToJSON,
} from '../models/index';

export interface GetPageSettingsRequest {
    languageCode?: string;
}

export interface PutUpdateSettingRequest {
    setting: Omit<Setting, '$schema'>;
}

/**
 * 
 */
export class SettingApi extends runtime.BaseAPI {

    /**
     * Get page settings by language code.
     * Get page settings
     */
    async getPageSettingsRaw(requestParameters: GetPageSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SettingPageBody>> {
        const queryParameters: any = {};

        if (requestParameters['languageCode'] != null) {
            queryParameters['language_code'] = requestParameters['languageCode'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/settings`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SettingPageBodyFromJSON(jsonValue));
    }

    /**
     * Get page settings by language code.
     * Get page settings
     */
    async getPageSettings(requestParameters: GetPageSettingsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SettingPageBody> {
        const response = await this.getPageSettingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update page settings.
     * Update setting
     */
    async putUpdateSettingRaw(requestParameters: PutUpdateSettingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SettingPageBody>> {
        if (requestParameters['setting'] == null) {
            throw new runtime.RequiredError(
                'setting',
                'Required parameter "setting" was null or undefined when calling putUpdateSetting().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/settings`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SettingToJSON(requestParameters['setting']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SettingPageBodyFromJSON(jsonValue));
    }

    /**
     * Update page settings.
     * Update setting
     */
    async putUpdateSetting(requestParameters: PutUpdateSettingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SettingPageBody> {
        const response = await this.putUpdateSettingRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
