/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorModel,
  Setting,
  SettingBatchRequestBody,
  SettingBatchResponseBody,
  SettingPageBody,
} from '../models/index';
import {
    ErrorModelFromJSON,
    ErrorModelToJSON,
    SettingFromJSON,
    SettingToJSON,
    SettingBatchRequestBodyFromJSON,
    SettingBatchRequestBodyToJSON,
    SettingBatchResponseBodyFromJSON,
    SettingBatchResponseBodyToJSON,
    SettingPageBodyFromJSON,
    SettingPageBodyToJSON,
} from '../models/index';

export interface GetPageSettingsRequest {
    languageCode?: string;
}

export interface PutUpdateSettingRequest {
    setting: Omit<Setting, '$schema'>;
}

export interface PutUpdateSettingsBatchRequest {
    settingBatchRequestBody: Omit<SettingBatchRequestBody, '$schema'>;
}

/**
 * 
 */
export class SettingApi extends runtime.BaseAPI {

    /**
     * Get page settings by language code. Used to render the public site shell (title, contact info, legal pages, ...) and requires no authentication.
     * Get page settings
     */
    async getPageSettingsRaw(requestParameters: GetPageSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SettingPageBody>> {
        const queryParameters: any = {};

        if (requestParameters['languageCode'] != null) {
            queryParameters['language_code'] = requestParameters['languageCode'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/settings`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SettingPageBodyFromJSON(jsonValue));
    }

    /**
     * Get page settings by language code. Used to render the public site shell (title, contact info, legal pages, ...) and requires no authentication.
     * Get page settings
     */
    async getPageSettings(requestParameters: GetPageSettingsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SettingPageBody> {
        const response = await this.getPageSettingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update page settings.
     * Update setting
     */
    async putUpdateSettingRaw(requestParameters: PutUpdateSettingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SettingPageBody>> {
        if (requestParameters['setting'] == null) {
            throw new runtime.RequiredError(
                'setting',
                'Required parameter "setting" was null or undefined when calling putUpdateSetting().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/settings`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SettingToJSON(requestParameters['setting']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SettingPageBodyFromJSON(jsonValue));
    }

    /**
     * Update page settings.
     * Update setting
     */
    async putUpdateSetting(requestParameters: PutUpdateSettingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SettingPageBody> {
        const response = await this.putUpdateSettingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update many page settings in a single request. Invalid items are rejected individually (reported in the response\'s failures list) without aborting the rest of the batch.
     * Update settings in batch
     */
    async putUpdateSettingsBatchRaw(requestParameters: PutUpdateSettingsBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SettingBatchResponseBody>> {
        if (requestParameters['settingBatchRequestBody'] == null) {
            throw new runtime.RequiredError(
                'settingBatchRequestBody',
                'Required parameter "settingBatchRequestBody" was null or undefined when calling putUpdateSettingsBatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/settings/batch`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SettingBatchRequestBodyToJSON(requestParameters['settingBatchRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SettingBatchResponseBodyFromJSON(jsonValue));
    }

    /**
     * Update many page settings in a single request. Invalid items are rejected individually (reported in the response\'s failures list) without aborting the rest of the batch.
     * Update settings in batch
     */
    async putUpdateSettingsBatch(requestParameters: PutUpdateSettingsBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SettingBatchResponseBody> {
        const response = await this.putUpdateSettingsBatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
