/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorModel,
  PublicShelf,
  Shelf,
  ShelfBase,
} from '../models/index';
import {
    ErrorModelFromJSON,
    ErrorModelToJSON,
    PublicShelfFromJSON,
    PublicShelfToJSON,
    ShelfFromJSON,
    ShelfToJSON,
    ShelfBaseFromJSON,
    ShelfBaseToJSON,
} from '../models/index';

export interface DeleteShelfRequest {
    shelfId: string;
}

export interface GetPublicShelfByPathRequest {
    path: string;
}

export interface GetShelfByIdRequest {
    shelfId: string;
}

export interface PostCreateShelfRequest {
    shelfBase: Omit<ShelfBase, '$schema'>;
}

export interface PutUpdateShelfRequest {
    shelfId: string;
    shelfBase: Omit<ShelfBase, '$schema'>;
}

/**
 * 
 */
export class ShelfApi extends runtime.BaseAPI {

    /**
     * Delete a shelf by ID.
     * Delete shelf
     */
    async deleteShelfRaw(requestParameters: DeleteShelfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['shelfId'] == null) {
            throw new runtime.RequiredError(
                'shelfId',
                'Required parameter "shelfId" was null or undefined when calling deleteShelf().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/shelves/{shelfId}`;
        urlPath = urlPath.replace(`{${"shelfId"}}`, encodeURIComponent(String(requestParameters['shelfId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a shelf by ID.
     * Delete shelf
     */
    async deleteShelf(requestParameters: DeleteShelfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteShelfRaw(requestParameters, initOverrides);
    }

    /**
     * Get the public-safe view of a shelf by its path. Used to render a shelf\'s public link page and requires no authentication.
     * Get public shelf by path
     */
    async getPublicShelfByPathRaw(requestParameters: GetPublicShelfByPathRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicShelf>> {
        if (requestParameters['path'] == null) {
            throw new runtime.RequiredError(
                'path',
                'Required parameter "path" was null or undefined when calling getPublicShelfByPath().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/shelves/by-path/{path}`;
        urlPath = urlPath.replace(`{${"path"}}`, encodeURIComponent(String(requestParameters['path'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicShelfFromJSON(jsonValue));
    }

    /**
     * Get the public-safe view of a shelf by its path. Used to render a shelf\'s public link page and requires no authentication.
     * Get public shelf by path
     */
    async getPublicShelfByPath(requestParameters: GetPublicShelfByPathRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicShelf> {
        const response = await this.getPublicShelfByPathRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a shelf by ID.
     * Get shelf by ID
     */
    async getShelfByIdRaw(requestParameters: GetShelfByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Shelf>> {
        if (requestParameters['shelfId'] == null) {
            throw new runtime.RequiredError(
                'shelfId',
                'Required parameter "shelfId" was null or undefined when calling getShelfById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/shelves/{shelfId}`;
        urlPath = urlPath.replace(`{${"shelfId"}}`, encodeURIComponent(String(requestParameters['shelfId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ShelfFromJSON(jsonValue));
    }

    /**
     * Get a shelf by ID.
     * Get shelf by ID
     */
    async getShelfById(requestParameters: GetShelfByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Shelf> {
        const response = await this.getShelfByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all shelves.
     * List shelves
     */
    async listShelvesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Shelf>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/shelves`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ShelfFromJSON));
    }

    /**
     * List all shelves.
     * List shelves
     */
    async listShelves(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Shelf>> {
        const response = await this.listShelvesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Create a new shelf.
     * Create shelf
     */
    async postCreateShelfRaw(requestParameters: PostCreateShelfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Shelf>> {
        if (requestParameters['shelfBase'] == null) {
            throw new runtime.RequiredError(
                'shelfBase',
                'Required parameter "shelfBase" was null or undefined when calling postCreateShelf().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/shelves`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ShelfBaseToJSON(requestParameters['shelfBase']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ShelfFromJSON(jsonValue));
    }

    /**
     * Create a new shelf.
     * Create shelf
     */
    async postCreateShelf(requestParameters: PostCreateShelfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Shelf> {
        const response = await this.postCreateShelfRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an existing shelf.
     * Update shelf
     */
    async putUpdateShelfRaw(requestParameters: PutUpdateShelfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Shelf>> {
        if (requestParameters['shelfId'] == null) {
            throw new runtime.RequiredError(
                'shelfId',
                'Required parameter "shelfId" was null or undefined when calling putUpdateShelf().'
            );
        }

        if (requestParameters['shelfBase'] == null) {
            throw new runtime.RequiredError(
                'shelfBase',
                'Required parameter "shelfBase" was null or undefined when calling putUpdateShelf().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/shelves/{shelfId}`;
        urlPath = urlPath.replace(`{${"shelfId"}}`, encodeURIComponent(String(requestParameters['shelfId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ShelfBaseToJSON(requestParameters['shelfBase']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ShelfFromJSON(jsonValue));
    }

    /**
     * Update an existing shelf.
     * Update shelf
     */
    async putUpdateShelf(requestParameters: PutUpdateShelfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Shelf> {
        const response = await this.putUpdateShelfRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
