/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorModel,
  Statistic,
} from '../models/index';
import {
    ErrorModelFromJSON,
    ErrorModelToJSON,
    StatisticFromJSON,
    StatisticToJSON,
} from '../models/index';

/**
 * 
 */
export class StatisticApi extends runtime.BaseAPI {

    /**
     * Get usage statistics for the current user.
     * Get statistic
     */
    async getStatisticRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Statistic>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/statistics`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StatisticFromJSON(jsonValue));
    }

    /**
     * Get usage statistics for the current user.
     * Get statistic
     */
    async getStatistic(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Statistic> {
        const response = await this.getStatisticRaw(initOverrides);
        return await response.value();
    }

}
