/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorModel,
  Theme,
  ThemeBase,
  ThemeGroupedResponseBody,
} from '../models/index';
import {
    ErrorModelFromJSON,
    ErrorModelToJSON,
    ThemeFromJSON,
    ThemeToJSON,
    ThemeBaseFromJSON,
    ThemeBaseToJSON,
    ThemeGroupedResponseBodyFromJSON,
    ThemeGroupedResponseBodyToJSON,
} from '../models/index';

export interface DeleteThemeRequest {
    themeId: string;
}

export interface GetThemeByIdRequest {
    themeId: string;
}

export interface PostCreateThemeRequest {
    themeBase: Omit<ThemeBase, '$schema'>;
}

export interface PutUpdateThemeRequest {
    themeId: string;
    themeBase: Omit<ThemeBase, '$schema'>;
}

/**
 * 
 */
export class ThemeApi extends runtime.BaseAPI {

    /**
     * Delete a theme by ID. Its owner or an admin may delete a user theme; instance themes can never be deleted through the API.
     * Delete theme
     */
    async deleteThemeRaw(requestParameters: DeleteThemeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['themeId'] == null) {
            throw new runtime.RequiredError(
                'themeId',
                'Required parameter "themeId" was null or undefined when calling deleteTheme().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/themes/{themeId}`;
        urlPath = urlPath.replace(`{${"themeId"}}`, encodeURIComponent(String(requestParameters['themeId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a theme by ID. Its owner or an admin may delete a user theme; instance themes can never be deleted through the API.
     * Delete theme
     */
    async deleteTheme(requestParameters: DeleteThemeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteThemeRaw(requestParameters, initOverrides);
    }

    /**
     * Get a theme by ID. Instance themes are readable by any authenticated caller; user themes only by their owner or an admin.
     * Get theme by ID
     */
    async getThemeByIdRaw(requestParameters: GetThemeByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Theme>> {
        if (requestParameters['themeId'] == null) {
            throw new runtime.RequiredError(
                'themeId',
                'Required parameter "themeId" was null or undefined when calling getThemeById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/themes/{themeId}`;
        urlPath = urlPath.replace(`{${"themeId"}}`, encodeURIComponent(String(requestParameters['themeId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ThemeFromJSON(jsonValue));
    }

    /**
     * Get a theme by ID. Instance themes are readable by any authenticated caller; user themes only by their owner or an admin.
     * Get theme by ID
     */
    async getThemeById(requestParameters: GetThemeByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Theme> {
        const response = await this.getThemeByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List every user-created theme across the instance, for moderation. Admin only.
     * List all user themes
     */
    async listAllUserThemesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Theme>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/themes/admin`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ThemeFromJSON));
    }

    /**
     * List every user-created theme across the instance, for moderation. Admin only.
     * List all user themes
     */
    async listAllUserThemes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Theme>> {
        const response = await this.listAllUserThemesRaw(initOverrides);
        return await response.value();
    }

    /**
     * List themes available to the caller, grouped into instance-provided and their own.
     * List themes
     */
    async listThemesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ThemeGroupedResponseBody>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/themes`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ThemeGroupedResponseBodyFromJSON(jsonValue));
    }

    /**
     * List themes available to the caller, grouped into instance-provided and their own.
     * List themes
     */
    async listThemes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ThemeGroupedResponseBody> {
        const response = await this.listThemesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Create a new theme, owned by the authenticated caller.
     * Create theme
     */
    async postCreateThemeRaw(requestParameters: PostCreateThemeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Theme>> {
        if (requestParameters['themeBase'] == null) {
            throw new runtime.RequiredError(
                'themeBase',
                'Required parameter "themeBase" was null or undefined when calling postCreateTheme().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/themes`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ThemeBaseToJSON(requestParameters['themeBase']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ThemeFromJSON(jsonValue));
    }

    /**
     * Create a new theme, owned by the authenticated caller.
     * Create theme
     */
    async postCreateTheme(requestParameters: PostCreateThemeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Theme> {
        const response = await this.postCreateThemeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an existing theme. Only its owner may update it - not even an admin, and never an instance theme (managed via the mounted directory instead).
     * Update theme
     */
    async putUpdateThemeRaw(requestParameters: PutUpdateThemeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Theme>> {
        if (requestParameters['themeId'] == null) {
            throw new runtime.RequiredError(
                'themeId',
                'Required parameter "themeId" was null or undefined when calling putUpdateTheme().'
            );
        }

        if (requestParameters['themeBase'] == null) {
            throw new runtime.RequiredError(
                'themeBase',
                'Required parameter "themeBase" was null or undefined when calling putUpdateTheme().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/themes/{themeId}`;
        urlPath = urlPath.replace(`{${"themeId"}}`, encodeURIComponent(String(requestParameters['themeId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ThemeBaseToJSON(requestParameters['themeBase']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ThemeFromJSON(jsonValue));
    }

    /**
     * Update an existing theme. Only its owner may update it - not even an admin, and never an instance theme (managed via the mounted directory instead).
     * Update theme
     */
    async putUpdateTheme(requestParameters: PutUpdateThemeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Theme> {
        const response = await this.putUpdateThemeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
