/* tslint:disable */
/* eslint-disable */
/**
 * LinkShelf
 * LinkShelf is an OpenSource alternative to linktree.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorModel,
  User,
  UserBase,
  UserRequestBodyOnlyPassword,
} from '../models/index';
import {
    ErrorModelFromJSON,
    ErrorModelToJSON,
    UserFromJSON,
    UserToJSON,
    UserBaseFromJSON,
    UserBaseToJSON,
    UserRequestBodyOnlyPasswordFromJSON,
    UserRequestBodyOnlyPasswordToJSON,
} from '../models/index';

export interface DeleteUserRequest {
    userId: string;
}

export interface GetUserByIdRequest {
    userId: string;
}

export interface PatchUserPasswordRequest {
    userId: string;
    userRequestBodyOnlyPassword: Omit<UserRequestBodyOnlyPassword, '$schema'>;
}

export interface PostCreateUserRequest {
    userBase: Omit<UserBase, '$schema'>;
}

export interface PutUpdateUserRequest {
    userId: string;
    userBase: Omit<UserBase, '$schema'>;
}

/**
 * 
 */
export class UserApi extends runtime.BaseAPI {

    /**
     * Delete a user by ID.
     * Delete user
     */
    async deleteUserRaw(requestParameters: DeleteUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling deleteUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/users/{userId}`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a user by ID.
     * Delete user
     */
    async deleteUser(requestParameters: DeleteUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteUserRaw(requestParameters, initOverrides);
    }

    /**
     * Get a user by ID.
     * Get user by ID
     */
    async getUserByIdRaw(requestParameters: GetUserByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getUserById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/users/{userId}`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
    }

    /**
     * Get a user by ID.
     * Get user by ID
     */
    async getUserById(requestParameters: GetUserByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User> {
        const response = await this.getUserByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Patch a user\'s password.
     * Patch user password
     */
    async patchUserPasswordRaw(requestParameters: PatchUserPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling patchUserPassword().'
            );
        }

        if (requestParameters['userRequestBodyOnlyPassword'] == null) {
            throw new runtime.RequiredError(
                'userRequestBodyOnlyPassword',
                'Required parameter "userRequestBodyOnlyPassword" was null or undefined when calling patchUserPassword().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/users/{userId}/password`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UserRequestBodyOnlyPasswordToJSON(requestParameters['userRequestBodyOnlyPassword']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Patch a user\'s password.
     * Patch user password
     */
    async patchUserPassword(requestParameters: PatchUserPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.patchUserPasswordRaw(requestParameters, initOverrides);
    }

    /**
     * Create a new user.
     * Create user
     */
    async postCreateUserRaw(requestParameters: PostCreateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>> {
        if (requestParameters['userBase'] == null) {
            throw new runtime.RequiredError(
                'userBase',
                'Required parameter "userBase" was null or undefined when calling postCreateUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/users`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserBaseToJSON(requestParameters['userBase']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
    }

    /**
     * Create a new user.
     * Create user
     */
    async postCreateUser(requestParameters: PostCreateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User> {
        const response = await this.postCreateUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an existing user. Consider that password updates are not handled here.
     * Update user
     */
    async putUpdateUserRaw(requestParameters: PutUpdateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling putUpdateUser().'
            );
        }

        if (requestParameters['userBase'] == null) {
            throw new runtime.RequiredError(
                'userBase',
                'Required parameter "userBase" was null or undefined when calling putUpdateUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/users/{userId}`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UserBaseToJSON(requestParameters['userBase']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
    }

    /**
     * Update an existing user. Consider that password updates are not handled here.
     * Update user
     */
    async putUpdateUser(requestParameters: PutUpdateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User> {
        const response = await this.putUpdateUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
