// Code generated by MockGen. DO NOT EDIT.
// Source: email_action_token.go
//
// Generated by this command:
//
//	mockgen -source=email_action_token.go -destination=mocks/email_action_token_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	repository "backend/internal/infrastructure/repository"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockEmailActionTokenRepository is a mock of EmailActionTokenRepository interface.
type MockEmailActionTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEmailActionTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockEmailActionTokenRepositoryMockRecorder is the mock recorder for MockEmailActionTokenRepository.
type MockEmailActionTokenRepositoryMockRecorder struct {
	mock *MockEmailActionTokenRepository
}

// NewMockEmailActionTokenRepository creates a new mock instance.
func NewMockEmailActionTokenRepository(ctrl *gomock.Controller) *MockEmailActionTokenRepository {
	mock := &MockEmailActionTokenRepository{ctrl: ctrl}
	mock.recorder = &MockEmailActionTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailActionTokenRepository) EXPECT() *MockEmailActionTokenRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEmailActionTokenRepository) Create(userId, tokenHash, action string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", userId, tokenHash, action, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockEmailActionTokenRepositoryMockRecorder) Create(userId, tokenHash, action, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEmailActionTokenRepository)(nil).Create), userId, tokenHash, action, expiresAt)
}

// DeleteByUserIdAndAction mocks base method.
func (m *MockEmailActionTokenRepository) DeleteByUserIdAndAction(userId, action string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserIdAndAction", userId, action)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserIdAndAction indicates an expected call of DeleteByUserIdAndAction.
func (mr *MockEmailActionTokenRepositoryMockRecorder) DeleteByUserIdAndAction(userId, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserIdAndAction", reflect.TypeOf((*MockEmailActionTokenRepository)(nil).DeleteByUserIdAndAction), userId, action)
}

// GetByHash mocks base method.
func (m *MockEmailActionTokenRepository) GetByHash(tokenHash string) (*repository.EmailActionToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByHash", tokenHash)
	ret0, _ := ret[0].(*repository.EmailActionToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByHash indicates an expected call of GetByHash.
func (mr *MockEmailActionTokenRepositoryMockRecorder) GetByHash(tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByHash", reflect.TypeOf((*MockEmailActionTokenRepository)(nil).GetByHash), tokenHash)
}

// GetLatestByUserIdAndAction mocks base method.
func (m *MockEmailActionTokenRepository) GetLatestByUserIdAndAction(userId, action string) (*repository.EmailActionToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestByUserIdAndAction", userId, action)
	ret0, _ := ret[0].(*repository.EmailActionToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestByUserIdAndAction indicates an expected call of GetLatestByUserIdAndAction.
func (mr *MockEmailActionTokenRepositoryMockRecorder) GetLatestByUserIdAndAction(userId, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestByUserIdAndAction", reflect.TypeOf((*MockEmailActionTokenRepository)(nil).GetLatestByUserIdAndAction), userId, action)
}
