// Code generated by MockGen. DO NOT EDIT.
// Source: link.go
//
// Generated by this command:
//
//	mockgen -source=link.go -destination=mocks/link_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	model "backend/internal/infrastructure/api/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLinkRepository is a mock of LinkRepository interface.
type MockLinkRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLinkRepositoryMockRecorder
	isgomock struct{}
}

// MockLinkRepositoryMockRecorder is the mock recorder for MockLinkRepository.
type MockLinkRepositoryMockRecorder struct {
	mock *MockLinkRepository
}

// NewMockLinkRepository creates a new mock instance.
func NewMockLinkRepository(ctrl *gomock.Controller) *MockLinkRepository {
	mock := &MockLinkRepository{ctrl: ctrl}
	mock.recorder = &MockLinkRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkRepository) EXPECT() *MockLinkRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLinkRepository) Create(l *model.Link) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", l)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockLinkRepositoryMockRecorder) Create(l any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLinkRepository)(nil).Create), l)
}

// Delete mocks base method.
func (m *MockLinkRepository) Delete(l *model.Link) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", l)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLinkRepositoryMockRecorder) Delete(l any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLinkRepository)(nil).Delete), l)
}

// Get mocks base method.
func (m *MockLinkRepository) Get(id string) (*model.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(*model.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockLinkRepositoryMockRecorder) Get(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockLinkRepository)(nil).Get), id)
}

// ListByShelfId mocks base method.
func (m *MockLinkRepository) ListByShelfId(id string) ([]model.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByShelfId", id)
	ret0, _ := ret[0].([]model.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByShelfId indicates an expected call of ListByShelfId.
func (mr *MockLinkRepositoryMockRecorder) ListByShelfId(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByShelfId", reflect.TypeOf((*MockLinkRepository)(nil).ListByShelfId), id)
}

// Update mocks base method.
func (m *MockLinkRepository) Update(l *model.Link) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", l)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockLinkRepositoryMockRecorder) Update(l any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLinkRepository)(nil).Update), l)
}
