// Code generated by MockGen. DO NOT EDIT.
// Source: oidc_state.go
//
// Generated by this command:
//
//	mockgen -source=oidc_state.go -destination=mocks/oidc_state_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	repository "backend/internal/infrastructure/repository"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockOidcStateRepository is a mock of OidcStateRepository interface.
type MockOidcStateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOidcStateRepositoryMockRecorder
	isgomock struct{}
}

// MockOidcStateRepositoryMockRecorder is the mock recorder for MockOidcStateRepository.
type MockOidcStateRepositoryMockRecorder struct {
	mock *MockOidcStateRepository
}

// NewMockOidcStateRepository creates a new mock instance.
func NewMockOidcStateRepository(ctrl *gomock.Controller) *MockOidcStateRepository {
	mock := &MockOidcStateRepository{ctrl: ctrl}
	mock.recorder = &MockOidcStateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOidcStateRepository) EXPECT() *MockOidcStateRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOidcStateRepository) Create(state, codeVerifier string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", state, codeVerifier, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOidcStateRepositoryMockRecorder) Create(state, codeVerifier, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOidcStateRepository)(nil).Create), state, codeVerifier, expiresAt)
}

// DeleteByState mocks base method.
func (m *MockOidcStateRepository) DeleteByState(state string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByState", state)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByState indicates an expected call of DeleteByState.
func (mr *MockOidcStateRepositoryMockRecorder) DeleteByState(state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByState", reflect.TypeOf((*MockOidcStateRepository)(nil).DeleteByState), state)
}

// GetByState mocks base method.
func (m *MockOidcStateRepository) GetByState(state string) (*repository.OidcState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByState", state)
	ret0, _ := ret[0].(*repository.OidcState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByState indicates an expected call of GetByState.
func (mr *MockOidcStateRepositoryMockRecorder) GetByState(state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByState", reflect.TypeOf((*MockOidcStateRepository)(nil).GetByState), state)
}
