// Code generated by MockGen. DO NOT EDIT.
// Source: section.go
//
// Generated by this command:
//
//	mockgen -source=section.go -destination=mocks/section_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	model "backend/internal/infrastructure/api/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSectionRepository is a mock of SectionRepository interface.
type MockSectionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSectionRepositoryMockRecorder
	isgomock struct{}
}

// MockSectionRepositoryMockRecorder is the mock recorder for MockSectionRepository.
type MockSectionRepositoryMockRecorder struct {
	mock *MockSectionRepository
}

// NewMockSectionRepository creates a new mock instance.
func NewMockSectionRepository(ctrl *gomock.Controller) *MockSectionRepository {
	mock := &MockSectionRepository{ctrl: ctrl}
	mock.recorder = &MockSectionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSectionRepository) EXPECT() *MockSectionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSectionRepository) Create(s *model.Section) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", s)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSectionRepositoryMockRecorder) Create(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSectionRepository)(nil).Create), s)
}

// Delete mocks base method.
func (m *MockSectionRepository) Delete(s *model.Section) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSectionRepositoryMockRecorder) Delete(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSectionRepository)(nil).Delete), s)
}

// Get mocks base method.
func (m *MockSectionRepository) Get(id string) (*model.Section, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(*model.Section)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSectionRepositoryMockRecorder) Get(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSectionRepository)(nil).Get), id)
}

// ListByShelfId mocks base method.
func (m *MockSectionRepository) ListByShelfId(id string) ([]model.Section, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByShelfId", id)
	ret0, _ := ret[0].([]model.Section)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByShelfId indicates an expected call of ListByShelfId.
func (mr *MockSectionRepositoryMockRecorder) ListByShelfId(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByShelfId", reflect.TypeOf((*MockSectionRepository)(nil).ListByShelfId), id)
}

// Update mocks base method.
func (m *MockSectionRepository) Update(s *model.Section) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSectionRepositoryMockRecorder) Update(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSectionRepository)(nil).Update), s)
}
