// Code generated by MockGen. DO NOT EDIT.
// Source: setting.go
//
// Generated by this command:
//
//	mockgen -source=setting.go -destination=mocks/setting_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	model "backend/internal/infrastructure/api/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSettingRepository is a mock of SettingRepository interface.
type MockSettingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSettingRepositoryMockRecorder
	isgomock struct{}
}

// MockSettingRepositoryMockRecorder is the mock recorder for MockSettingRepository.
type MockSettingRepositoryMockRecorder struct {
	mock *MockSettingRepository
}

// NewMockSettingRepository creates a new mock instance.
func NewMockSettingRepository(ctrl *gomock.Controller) *MockSettingRepository {
	mock := &MockSettingRepository{ctrl: ctrl}
	mock.recorder = &MockSettingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettingRepository) EXPECT() *MockSettingRepositoryMockRecorder {
	return m.recorder
}

// GetByKey mocks base method.
func (m *MockSettingRepository) GetByKey(key string) (*model.Setting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByKey", key)
	ret0, _ := ret[0].(*model.Setting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByKey indicates an expected call of GetByKey.
func (mr *MockSettingRepositoryMockRecorder) GetByKey(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByKey", reflect.TypeOf((*MockSettingRepository)(nil).GetByKey), key)
}

// List mocks base method.
func (m *MockSettingRepository) List() ([]model.Setting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]model.Setting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSettingRepositoryMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSettingRepository)(nil).List))
}

// Update mocks base method.
func (m *MockSettingRepository) Update(key, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSettingRepositoryMockRecorder) Update(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSettingRepository)(nil).Update), key, value)
}
