// Code generated by MockGen. DO NOT EDIT.
// Source: shelf.go
//
// Generated by this command:
//
//	mockgen -source=shelf.go -destination=mocks/shelf_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	model "backend/internal/infrastructure/api/model"
	repository "backend/internal/infrastructure/repository"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockShelfRepository is a mock of ShelfRepository interface.
type MockShelfRepository struct {
	ctrl     *gomock.Controller
	recorder *MockShelfRepositoryMockRecorder
	isgomock struct{}
}

// MockShelfRepositoryMockRecorder is the mock recorder for MockShelfRepository.
type MockShelfRepositoryMockRecorder struct {
	mock *MockShelfRepository
}

// NewMockShelfRepository creates a new mock instance.
func NewMockShelfRepository(ctrl *gomock.Controller) *MockShelfRepository {
	mock := &MockShelfRepository{ctrl: ctrl}
	mock.recorder = &MockShelfRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShelfRepository) EXPECT() *MockShelfRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockShelfRepository) Create(s *model.Shelf) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", s)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockShelfRepositoryMockRecorder) Create(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockShelfRepository)(nil).Create), s)
}

// Delete mocks base method.
func (m *MockShelfRepository) Delete(s *model.Shelf) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockShelfRepositoryMockRecorder) Delete(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockShelfRepository)(nil).Delete), s)
}

// DomainInUse mocks base method.
func (m *MockShelfRepository) DomainInUse(domain, exceptShelfId string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DomainInUse", domain, exceptShelfId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DomainInUse indicates an expected call of DomainInUse.
func (mr *MockShelfRepositoryMockRecorder) DomainInUse(domain, exceptShelfId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DomainInUse", reflect.TypeOf((*MockShelfRepository)(nil).DomainInUse), domain, exceptShelfId)
}

// Get mocks base method.
func (m *MockShelfRepository) Get(id string) (*model.Shelf, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(*model.Shelf)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockShelfRepositoryMockRecorder) Get(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockShelfRepository)(nil).Get), id)
}

// GetByDomain mocks base method.
func (m *MockShelfRepository) GetByDomain(domain string) (*model.Shelf, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDomain", domain)
	ret0, _ := ret[0].(*model.Shelf)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDomain indicates an expected call of GetByDomain.
func (mr *MockShelfRepositoryMockRecorder) GetByDomain(domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDomain", reflect.TypeOf((*MockShelfRepository)(nil).GetByDomain), domain)
}

// GetByPath mocks base method.
func (m *MockShelfRepository) GetByPath(path string) (*model.Shelf, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPath", path)
	ret0, _ := ret[0].(*model.Shelf)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPath indicates an expected call of GetByPath.
func (mr *MockShelfRepositoryMockRecorder) GetByPath(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPath", reflect.TypeOf((*MockShelfRepository)(nil).GetByPath), path)
}

// GetByUsernameAndPath mocks base method.
func (m *MockShelfRepository) GetByUsernameAndPath(username, path string) (*model.Shelf, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsernameAndPath", username, path)
	ret0, _ := ret[0].(*model.Shelf)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUsernameAndPath indicates an expected call of GetByUsernameAndPath.
func (mr *MockShelfRepositoryMockRecorder) GetByUsernameAndPath(username, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsernameAndPath", reflect.TypeOf((*MockShelfRepository)(nil).GetByUsernameAndPath), username, path)
}

// List mocks base method.
func (m *MockShelfRepository) List() ([]model.Shelf, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]model.Shelf)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockShelfRepositoryMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockShelfRepository)(nil).List))
}

// ListByUserId mocks base method.
func (m *MockShelfRepository) ListByUserId(userId string) ([]model.Shelf, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserId", userId)
	ret0, _ := ret[0].([]model.Shelf)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserId indicates an expected call of ListByUserId.
func (mr *MockShelfRepositoryMockRecorder) ListByUserId(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserId", reflect.TypeOf((*MockShelfRepository)(nil).ListByUserId), userId)
}

// ListPathCollisions mocks base method.
func (m *MockShelfRepository) ListPathCollisions() ([]repository.PathCollision, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPathCollisions")
	ret0, _ := ret[0].([]repository.PathCollision)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPathCollisions indicates an expected call of ListPathCollisions.
func (mr *MockShelfRepositoryMockRecorder) ListPathCollisions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPathCollisions", reflect.TypeOf((*MockShelfRepository)(nil).ListPathCollisions))
}

// PathInUse mocks base method.
func (m *MockShelfRepository) PathInUse(path, exceptShelfId string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PathInUse", path, exceptShelfId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PathInUse indicates an expected call of PathInUse.
func (mr *MockShelfRepositoryMockRecorder) PathInUse(path, exceptShelfId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PathInUse", reflect.TypeOf((*MockShelfRepository)(nil).PathInUse), path, exceptShelfId)
}

// PathInUseByUser mocks base method.
func (m *MockShelfRepository) PathInUseByUser(userId, path, exceptShelfId string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PathInUseByUser", userId, path, exceptShelfId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PathInUseByUser indicates an expected call of PathInUseByUser.
func (mr *MockShelfRepositoryMockRecorder) PathInUseByUser(userId, path, exceptShelfId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PathInUseByUser", reflect.TypeOf((*MockShelfRepository)(nil).PathInUseByUser), userId, path, exceptShelfId)
}

// Update mocks base method.
func (m *MockShelfRepository) Update(s *model.Shelf) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockShelfRepositoryMockRecorder) Update(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockShelfRepository)(nil).Update), s)
}
