// Code generated by MockGen. DO NOT EDIT.
// Source: shelf.go
//
// Generated by this command:
//
//	mockgen -source=shelf.go -destination=mocks/shelf_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	model "backend/internal/infrastructure/api/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockShelfRepository is a mock of ShelfRepository interface.
type MockShelfRepository struct {
	ctrl     *gomock.Controller
	recorder *MockShelfRepositoryMockRecorder
	isgomock struct{}
}

// MockShelfRepositoryMockRecorder is the mock recorder for MockShelfRepository.
type MockShelfRepositoryMockRecorder struct {
	mock *MockShelfRepository
}

// NewMockShelfRepository creates a new mock instance.
func NewMockShelfRepository(ctrl *gomock.Controller) *MockShelfRepository {
	mock := &MockShelfRepository{ctrl: ctrl}
	mock.recorder = &MockShelfRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShelfRepository) EXPECT() *MockShelfRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockShelfRepository) Create(s *model.Shelf) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", s)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockShelfRepositoryMockRecorder) Create(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockShelfRepository)(nil).Create), s)
}

// Delete mocks base method.
func (m *MockShelfRepository) Delete(s *model.Shelf) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockShelfRepositoryMockRecorder) Delete(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockShelfRepository)(nil).Delete), s)
}

// Get mocks base method.
func (m *MockShelfRepository) Get(id string) (*model.Shelf, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(*model.Shelf)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockShelfRepositoryMockRecorder) Get(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockShelfRepository)(nil).Get), id)
}

// List mocks base method.
func (m *MockShelfRepository) List() (*model.Shelf, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].(*model.Shelf)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockShelfRepositoryMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockShelfRepository)(nil).List))
}

// Update mocks base method.
func (m *MockShelfRepository) Update(s *model.Shelf) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockShelfRepositoryMockRecorder) Update(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockShelfRepository)(nil).Update), s)
}
