// Code generated by MockGen. DO NOT EDIT.
// Source: statistic.go
//
// Generated by this command:
//
//	mockgen -source=statistic.go -destination=mocks/statistic_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStatisticRepository is a mock of StatisticRepository interface.
type MockStatisticRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStatisticRepositoryMockRecorder
	isgomock struct{}
}

// MockStatisticRepositoryMockRecorder is the mock recorder for MockStatisticRepository.
type MockStatisticRepositoryMockRecorder struct {
	mock *MockStatisticRepository
}

// NewMockStatisticRepository creates a new mock instance.
func NewMockStatisticRepository(ctrl *gomock.Controller) *MockStatisticRepository {
	mock := &MockStatisticRepository{ctrl: ctrl}
	mock.recorder = &MockStatisticRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatisticRepository) EXPECT() *MockStatisticRepositoryMockRecorder {
	return m.recorder
}

// GetLinkAmount mocks base method.
func (m *MockStatisticRepository) GetLinkAmount(userId string) (*int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinkAmount", userId)
	ret0, _ := ret[0].(*int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLinkAmount indicates an expected call of GetLinkAmount.
func (mr *MockStatisticRepositoryMockRecorder) GetLinkAmount(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinkAmount", reflect.TypeOf((*MockStatisticRepository)(nil).GetLinkAmount), userId)
}

// GetSectionAmount mocks base method.
func (m *MockStatisticRepository) GetSectionAmount(userId string) (*int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSectionAmount", userId)
	ret0, _ := ret[0].(*int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSectionAmount indicates an expected call of GetSectionAmount.
func (mr *MockStatisticRepositoryMockRecorder) GetSectionAmount(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSectionAmount", reflect.TypeOf((*MockStatisticRepository)(nil).GetSectionAmount), userId)
}

// GetShelfAmount mocks base method.
func (m *MockStatisticRepository) GetShelfAmount(userId string) (*int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShelfAmount", userId)
	ret0, _ := ret[0].(*int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShelfAmount indicates an expected call of GetShelfAmount.
func (mr *MockStatisticRepositoryMockRecorder) GetShelfAmount(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShelfAmount", reflect.TypeOf((*MockStatisticRepository)(nil).GetShelfAmount), userId)
}
