// Code generated by MockGen. DO NOT EDIT.
// Source: theme.go
//
// Generated by this command:
//
//	mockgen -source=theme.go -destination=mocks/theme_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	model "backend/internal/infrastructure/api/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockThemeRepository is a mock of ThemeRepository interface.
type MockThemeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockThemeRepositoryMockRecorder
	isgomock struct{}
}

// MockThemeRepositoryMockRecorder is the mock recorder for MockThemeRepository.
type MockThemeRepositoryMockRecorder struct {
	mock *MockThemeRepository
}

// NewMockThemeRepository creates a new mock instance.
func NewMockThemeRepository(ctrl *gomock.Controller) *MockThemeRepository {
	mock := &MockThemeRepository{ctrl: ctrl}
	mock.recorder = &MockThemeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockThemeRepository) EXPECT() *MockThemeRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockThemeRepository) Create(t *model.Theme) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", t)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockThemeRepositoryMockRecorder) Create(t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockThemeRepository)(nil).Create), t)
}

// Delete mocks base method.
func (m *MockThemeRepository) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockThemeRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockThemeRepository)(nil).Delete), id)
}

// DeleteInstanceNotIn mocks base method.
func (m *MockThemeRepository) DeleteInstanceNotIn(keepSourceFiles []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInstanceNotIn", keepSourceFiles)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInstanceNotIn indicates an expected call of DeleteInstanceNotIn.
func (mr *MockThemeRepositoryMockRecorder) DeleteInstanceNotIn(keepSourceFiles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInstanceNotIn", reflect.TypeOf((*MockThemeRepository)(nil).DeleteInstanceNotIn), keepSourceFiles)
}

// Get mocks base method.
func (m *MockThemeRepository) Get(id string) (*model.Theme, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(*model.Theme)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockThemeRepositoryMockRecorder) Get(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockThemeRepository)(nil).Get), id)
}

// GetBySourceFile mocks base method.
func (m *MockThemeRepository) GetBySourceFile(sourceFile string) (*model.Theme, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySourceFile", sourceFile)
	ret0, _ := ret[0].(*model.Theme)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySourceFile indicates an expected call of GetBySourceFile.
func (mr *MockThemeRepositoryMockRecorder) GetBySourceFile(sourceFile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySourceFile", reflect.TypeOf((*MockThemeRepository)(nil).GetBySourceFile), sourceFile)
}

// ListAllUserScoped mocks base method.
func (m *MockThemeRepository) ListAllUserScoped() ([]model.Theme, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllUserScoped")
	ret0, _ := ret[0].([]model.Theme)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllUserScoped indicates an expected call of ListAllUserScoped.
func (mr *MockThemeRepositoryMockRecorder) ListAllUserScoped() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllUserScoped", reflect.TypeOf((*MockThemeRepository)(nil).ListAllUserScoped))
}

// ListByOwner mocks base method.
func (m *MockThemeRepository) ListByOwner(ownerUserId string) ([]model.Theme, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByOwner", ownerUserId)
	ret0, _ := ret[0].([]model.Theme)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByOwner indicates an expected call of ListByOwner.
func (mr *MockThemeRepositoryMockRecorder) ListByOwner(ownerUserId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByOwner", reflect.TypeOf((*MockThemeRepository)(nil).ListByOwner), ownerUserId)
}

// ListInstance mocks base method.
func (m *MockThemeRepository) ListInstance() ([]model.Theme, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInstance")
	ret0, _ := ret[0].([]model.Theme)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInstance indicates an expected call of ListInstance.
func (mr *MockThemeRepositoryMockRecorder) ListInstance() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstance", reflect.TypeOf((*MockThemeRepository)(nil).ListInstance))
}

// Update mocks base method.
func (m *MockThemeRepository) Update(t *model.Theme) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockThemeRepositoryMockRecorder) Update(t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockThemeRepository)(nil).Update), t)
}

// UpsertInstanceBySourceFile mocks base method.
func (m *MockThemeRepository) UpsertInstanceBySourceFile(t *model.Theme) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertInstanceBySourceFile", t)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertInstanceBySourceFile indicates an expected call of UpsertInstanceBySourceFile.
func (mr *MockThemeRepositoryMockRecorder) UpsertInstanceBySourceFile(t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertInstanceBySourceFile", reflect.TypeOf((*MockThemeRepository)(nil).UpsertInstanceBySourceFile), t)
}
