// Code generated by MockGen. DO NOT EDIT.
// Source: user.go
//
// Generated by this command:
//
//	mockgen -source=user.go -destination=mocks/user_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	model "backend/internal/infrastructure/api/model"
	repository "backend/internal/infrastructure/repository"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepository) Create(u model.UserBase, hashedPassword, role string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", u, hashedPassword, role)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(u, hashedPassword, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), u, hashedPassword, role)
}

// CreateExternal mocks base method.
func (m *MockUserRepository) CreateExternal(email, firstName, lastName, provider, providerId string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateExternal", email, firstName, lastName, provider, providerId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateExternal indicates an expected call of CreateExternal.
func (mr *MockUserRepositoryMockRecorder) CreateExternal(email, firstName, lastName, provider, providerId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExternal", reflect.TypeOf((*MockUserRepository)(nil).CreateExternal), email, firstName, lastName, provider, providerId)
}

// Delete mocks base method.
func (m *MockUserRepository) Delete(u *model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", u)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserRepositoryMockRecorder) Delete(u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserRepository)(nil).Delete), u)
}

// FindByEmail mocks base method.
func (m *MockUserRepository) FindByEmail(email string) (*repository.AuthRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", email)
	ret0, _ := ret[0].(*repository.AuthRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockUserRepositoryMockRecorder) FindByEmail(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockUserRepository)(nil).FindByEmail), email)
}

// FindByProviderId mocks base method.
func (m *MockUserRepository) FindByProviderId(providerId string) (*repository.AuthRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProviderId", providerId)
	ret0, _ := ret[0].(*repository.AuthRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByProviderId indicates an expected call of FindByProviderId.
func (mr *MockUserRepositoryMockRecorder) FindByProviderId(providerId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProviderId", reflect.TypeOf((*MockUserRepository)(nil).FindByProviderId), providerId)
}

// Get mocks base method.
func (m *MockUserRepository) Get(id string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUserRepositoryMockRecorder) Get(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUserRepository)(nil).Get), id)
}

// GetPassword mocks base method.
func (m *MockUserRepository) GetPassword(id string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPassword", id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPassword indicates an expected call of GetPassword.
func (mr *MockUserRepositoryMockRecorder) GetPassword(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPassword", reflect.TypeOf((*MockUserRepository)(nil).GetPassword), id)
}

// LinkProvider mocks base method.
func (m *MockUserRepository) LinkProvider(userId, provider, providerId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkProvider", userId, provider, providerId)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkProvider indicates an expected call of LinkProvider.
func (mr *MockUserRepositoryMockRecorder) LinkProvider(userId, provider, providerId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkProvider", reflect.TypeOf((*MockUserRepository)(nil).LinkProvider), userId, provider, providerId)
}

// List mocks base method.
func (m *MockUserRepository) List() ([]model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockUserRepositoryMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUserRepository)(nil).List))
}

// PatchPassword mocks base method.
func (m *MockUserRepository) PatchPassword(id, hashedPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchPassword", id, hashedPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// PatchPassword indicates an expected call of PatchPassword.
func (mr *MockUserRepositoryMockRecorder) PatchPassword(id, hashedPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchPassword", reflect.TypeOf((*MockUserRepository)(nil).PatchPassword), id, hashedPassword)
}

// SetPasswordAndRole mocks base method.
func (m *MockUserRepository) SetPasswordAndRole(userId, hashedPassword, role string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPasswordAndRole", userId, hashedPassword, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPasswordAndRole indicates an expected call of SetPasswordAndRole.
func (mr *MockUserRepositoryMockRecorder) SetPasswordAndRole(userId, hashedPassword, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPasswordAndRole", reflect.TypeOf((*MockUserRepository)(nil).SetPasswordAndRole), userId, hashedPassword, role)
}

// Update mocks base method.
func (m *MockUserRepository) Update(u *model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", u)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserRepositoryMockRecorder) Update(u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepository)(nil).Update), u)
}
