# =========================
# Build Go backend
# =========================
FROM --platform=$BUILDPLATFORM golang:1.27-alpine@sha256:cf6fca6641884b8433441b2b0652976f975e1d0fdd26d177eaaf8596087f3125 AS go-builder

ARG IMAGE_NAME
ARG IMAGE_TAG
ARG TARGETOS
ARG TARGETARCH

ENV CGO_ENABLED=0
ENV GOOS=$TARGETOS
ENV GOARCH=$TARGETARCH

WORKDIR /app

# Cache deps
COPY backend/go.mod backend/go.sum ./
RUN go mod download

# Copy source
COPY backend/ .

# Build
RUN go build \
  -ldflags="-s -w -X main.sentryRelease=${IMAGE_NAME}:${IMAGE_TAG}" \
  -o /out/linkshelf \
  ./cmd/app/main.go

# =========================
# Build Nuxt frontend
# =========================
FROM node:26-alpine@sha256:0b36e8c136b94cd4fcf02188228e76c31ad5872eef3fec8cbd2eee500cfd9e80 AS nuxt-builder

RUN apk add --no-cache python3 make g++

WORKDIR /frontend

COPY frontend/package.json frontend/package-lock.json ./
RUN npm ci

COPY frontend .
RUN npm run build

ARG TARGETARCH
RUN NODE_ARCH=$([ "$TARGETARCH" = "arm64" ] && echo arm64 || echo x64) && \
  find .output/server/node_modules/better-sqlite3/prebuilds -type f \
    ! -name "linuxmusl-${NODE_ARCH}.node" -delete

# =========================
# Runtime
# =========================
FROM alpine:3.24@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6

# tini = tiny init, nothing more
RUN apk add --no-cache nodejs tini ca-certificates

RUN adduser -D -u 1001 -G root app

WORKDIR /app

COPY --from=go-builder --chown=1001:0 --chmod=755 /out/linkshelf /app/linkshelf
COPY --chown=1001:0 --chmod=644 ./backend/config.default.yaml /app/config.default.yaml
COPY --chown=1001:0 --chmod=755 ./backend/migrations /app/migrations
COPY --chown=1001:0 --chmod=644 ./backend/themes /app/themes
COPY --from=nuxt-builder --chown=1001:0 --chmod=755 /frontend/.output /app/.output

ENV NODE_ENV=production
ENV NITRO_PORT=3000
ENV NITRO_HOST=0.0.0.0
ENV HOME=/app

EXPOSE 8085
EXPOSE 3000

USER 1001

ENTRYPOINT ["/sbin/tini", "--"]

CMD ["sh", "-c", "/app/linkshelf & node /app/.output/server/index.mjs"]
